      { ku: 'پەنگوین', en: 'penguin', emoji: '🐧' },
      { ku: 'فیلی دەریایی', en: 'walrus', emoji: '🦭' },
      { ku: 'ئۆرکا', en: 'orca killer whale', emoji: '🐋' },
      { ku: 'قەپێلک', en: 'clam shell', emoji: '🐚' },
      { ku: 'ماسیی پفکەر', en: 'puffer fish', emoji: '🐡' },
      { ku: 'قرشە نەهەنگ', en: 'whale shark', emoji: '🦈' },
      { ku: 'مانای دەریایی', en: 'manatee', emoji: '🌊' },
      { ku: 'پلانکتۆن', en: 'plankton', emoji: '🦠' },
      { ku: 'سوفڕەماسی', en: 'stingray', emoji: '🐠' },
    ],
  },
  {
    id: 'birds', name: 'باڵندەکان', icon: '🦅',
    words: [
      { ku: 'هەڵۆ', en: 'eagle', emoji: '🦅' },
      { ku: 'کۆتر', en: 'pigeon', emoji: '🕊️' },
      { ku: 'کوندەپەپوو', en: 'owl', emoji: '🦉' },
      { ku: 'تاوس', en: 'peacock', emoji: '🦚' },
      { ku: 'تووتی', en: 'parrot', emoji: '🦜' },
      { ku: 'پەنگوین', en: 'penguin', emoji: '🐧' },
      { ku: 'فلامینگۆ', en: 'flamingo', emoji: '🦩' },
      { ku: 'مریشک', en: 'hen', emoji: '🐔' },
      { ku: 'کەڵەشێر', en: 'rooster', emoji: '🐓' },
      { ku: 'مراوی', en: 'duck', emoji: '🦆' },
      { ku: 'قاز', en: 'goose', emoji: '🪿' },
      { ku: 'قەلەموون', en: 'turkey bird', emoji: '🦃' },
      { ku: 'چۆلەکە', en: 'sparrow', emoji: '🐦' },
      { ku: 'بڵبڵ', en: 'nightingale songbird', emoji: '🐤' },
      { ku: 'قورنگ', en: 'crane bird', emoji: ' Swans ' },
      { ku: 'لەقڵەق', en: 'stork', emoji: '🦩' },
      { ku: 'قو', en: 'swan', emoji: '🦢' },
      { ku: 'باز', en: 'falcon', emoji: '🦅' },
      { ku: 'داڵ', en: 'vulture', emoji: '🦅' },
      { ku: 'قەلەڕەش', en: 'crow raven', emoji: '🐦‍⬛' },
      { ku: 'کەژۆڵە', en: 'magpie', emoji: '🐦' },
      { ku: 'مەلی سەقا', en: 'pelican', emoji: '🦤' },
      { ku: 'تووکان', en: 'toucan', emoji: '🦜' },
      { ku: 'باڵندەی شیلەمژ', en: 'hummingbird', emoji: '🐦' },
      { ku: 'دارکوتەر', en: 'woodpecker', emoji: '🐦' },
      { ku: 'وشترمل', en: 'ostrich', emoji: '🦤' },
      { ku: 'کوندەپەپوو', en: 'barn owl', emoji: '🦉' },
      { ku: 'کەو', en: 'partridge', emoji: '🐦' },
      { ku: 'کڕکڕانە', en: 'quail', emoji: '🐦' },
      { ku: 'نەوڕەس', en: 'seagull', emoji: '🕊️' },
    ],
  },
  {
    id: 'transport', name: 'هاتووچۆ', icon: '🚗',
    words: [
      { ku: 'ئۆتۆمبێل', en: 'car', emoji: '🚗' },
      { ku: 'پاس', en: 'bus', emoji: '🚌' },
      { ku: 'تاکسی', en: 'taxi cab', emoji: '🚕' },
      { ku: 'بارهەڵگر', en: 'truck lorry', emoji: '🚚' },
      { ku: 'ئۆتۆمبێلی پۆلیس', en: 'police car', emoji: '🚓' },
      { ku: 'ئەمبوڵانس', en: 'ambulance', emoji: '🚑' },
      { ku: 'ئۆتۆمبێلی ئاگرکوژێنەوە', en: 'fire truck', emoji: '🚒' },
      { ku: 'پاسکیل', en: 'bicycle', emoji: '🚲' },
      { ku: 'مۆتۆڕسکیل', en: 'motorcycle', emoji: '🏍️' },
      { ku: 'سکووتەر', en: 'scooter', emoji: '🛵' },
      { ku: 'شەمەندەفەر', en: 'train', emoji: '🚆' },
      { ku: 'شەمەندەفەری ژێر زەوی', en: 'metro subway', emoji: '🚇' },
      { ku: 'تراموای', en: 'tram', emoji: '🚊' },
      { ku: 'فڕۆکە', en: 'airplane', emoji: '✈️' },
      { ku: 'هێلیکۆپتەر', en: 'helicopter', emoji: '🚁' },
      { ku: 'کەشتی', en: 'ship', emoji: '🚢' },
      { ku: 'بەلەم', en: 'boat', emoji: '⛵' },
      { ku: 'بەلەمی چارۆکەدار', en: 'sailboat', emoji: '⛵' },
      { ku: 'ژێردەریایی', en: 'submarine', emoji: '🌊' },
      { ku: 'مووشەکی فەزایی', en: 'space rocket', emoji: '🚀' },
      { ku: 'باڵۆن', en: 'hot air balloon', emoji: '🎈' },
      { ku: 'تراکتۆر', en: 'tractor', emoji: '🚜' },
      { ku: 'جیپ', en: 'jeep suv', emoji: '🚙' },
      { ku: 'ئۆتۆمبێلی پێشبڕکێ', en: 'race car', emoji: '🏎️' },
      { ku: 'مینی پاس', en: 'minivan', emoji: '🚐' },
      { ku: 'پیکاب', en: 'pickup truck', emoji: '🛻' },
      { ku: 'تەلەفریک', en: 'cable car', emoji: '🚠' },
      { ku: 'تەختەی سکەیت', en: 'skateboard', emoji: '🛹' },
      { ku: 'عەرەبانە', en: 'horse carriage', emoji: '🛒' },
      { ku: 'فڕۆکەی جەنگی', en: 'fighter jet', emoji: '🛩️' },
      { ku: 'قایق', en: 'canoe kayak', emoji: '🛶' },
      { ku: 'تانک', en: 'army tank', emoji: '🪖' },
      { ku: 'لەنگەر', en: 'anchor', emoji: '⚓' },
      { ku: 'هەڵگری سکی', en: 'ski lift', emoji: '🚡' },
      { ku: 'پاسکیلی یەک تایە', en: 'unicycle', emoji: '🎪' },
    ],
  },
  {
    id: 'instruments', name: 'ئامێری مۆسیقا', icon: '🎸',
    words: [
      { ku: 'گیتار', en: 'guitar', emoji: '🎸' },
      { ku: 'پیانۆ', en: 'piano', emoji: '🎹' },
      { ku: 'کەمانچە', en: 'violin', emoji: '🎻' },
      { ku: 'دەهۆڵ', en: 'drum', emoji: '🥁' },
      { ku: 'فلووت', en: 'flute', emoji: '🪈' },
      { ku: 'تڕەمپێت', en: 'trumpet', emoji: '🎺' },
      { ku: 'ساکسۆفۆن', en: 'saxophone', emoji: '🎷' },
      { ku: 'ئەکۆردیۆن', en: 'accordion', emoji: '🪗' },
      { ku: 'هارپ', en: 'harp', emoji: '🎵' },
      { ku: 'تەمبوور', en: 'tanbur lute', emoji: '🪕' },
      { ku: 'عوود', en: 'oud instrument', emoji: '🪕' },
      { ku: 'دەف', en: 'tambourine daf', emoji: '🥁' },
      { ku: 'زڕنا', en: 'zurna horn', emoji: '🎺' },
      { ku: 'سەنتوور', en: 'santur dulcimer', emoji: '🎶' },
      { ku: 'کلارنێت', en: 'clarinet', emoji: '🎵' },
      { ku: 'سیلۆ', en: 'cello', emoji: '🎻' },
      { ku: 'کۆنترا باسی', en: 'double bass', emoji: '🎻' },
      { ku: 'بانجۆ', en: 'banjo', emoji: '🪕' },
      { ku: 'ماندۆلین', en: 'mandolin', emoji: '🪕' },
      { ku: 'سازدەم', en: 'harmonica', emoji: '🎶' },
      { ku: 'زایلۆفۆن', en: 'xylophone', emoji: '🎵' },
      { ku: 'سەنج', en: 'cymbals', emoji: '🥁' },
      { ku: 'گۆنگ', en: 'gong', emoji: '🔔' },
      { ku: 'ئۆرگ', en: 'electric organ keyboard', emoji: '🎹' },
      { ku: 'ترۆمبۆن', en: 'trombone', emoji: '🎺' },
      { ku: 'تۆبا', en: 'tuba', emoji: '🎺' },
      { ku: 'سینتسایزەر', en: 'synthesizer', emoji: '🎹' },
      { ku: 'ماراکاس', en: 'maracas', emoji: '🪇' },
      { ku: 'بۆنگۆ', en: 'bongo drums', emoji: '🥁' },
      { ku: 'تەپڵا', en: 'tabla drums', emoji: '🥁' },
    ],
  },
  {
    id: 'electronics', name: 'ئامێری ئەلیکترۆنی', icon: '💻',
    words: [
      { ku: 'کۆمپیوتەر', en: 'desktop computer', emoji: '🖥️' },
      { ku: 'لاپتۆپ', en: 'laptop', emoji: '💻' },
      { ku: 'مۆبایل', en: 'smartphone', emoji: '📱' },
      { ku: 'تابلێت', en: 'tablet', emoji: '📱' },
      { ku: 'تەلەفزیۆن', en: 'television screen', emoji: '📺' },
      { ku: 'کامێرا', en: 'digital camera', emoji: '📷' },
      { ku: 'تەختەکلیل', en: 'keyboard', emoji: '⌨️' },
      { ku: 'ماوس', en: 'computer mouse', emoji: '🖱️' },
      { ku: 'چاپکەر', en: 'printer', emoji: '🖨️' },
      { ku: 'بڵندگۆ', en: 'loudspeaker', emoji: '🔊' },
      { ku: 'بیستۆک', en: 'headphones', emoji: '🎧' },
      { ku: 'بیستۆکی بێتەل', en: 'wireless earbuds', emoji: '🎧' },
      { ku: 'مایکرۆفۆن', en: 'microphone', emoji: '🎤' },
      { ku: 'کاتژمێری زیرەک', en: 'smartwatch', emoji: '⌚' },
      { ku: 'ڕاوتەر', en: 'wifi router', emoji: '📶' },
      { ku: 'بارگاوییکەرەوە', en: 'phone charger', emoji: '🔌' },
      { ku: 'پاوەربانک', en: 'power bank', emoji: '🔋' },
      { ku: 'فلاش مێمۆری', en: 'usb flash drive', emoji: '💾' },
      { ku: 'هارد دیسک', en: 'hard drive', emoji: '💽' },
      { ku: 'پلەیستەیشن', en: 'game console', emoji: '🎮' },
      { ku: 'دەسکی یاری', en: 'game controller', emoji: '🎮' },
      { ku: 'درۆن', en: 'drone', emoji: '🚁' },
      { ku: 'پرۆجێکتەر', en: 'projector', emoji: '📽️' },
      { ku: 'سکانەر', en: 'scanner', emoji: '🖨️' },
      { ku: 'ریمۆت کۆنترۆڵ', en: 'tv remote control', emoji: '📺' },
      { ku: 'شاشەی کۆمپیوتەر', en: 'computer monitor', emoji: '🖥️' },
      { ku: 'وێبکام', en: 'webcam', emoji: '📹' },
      { ku: 'کامێرای ڤیدیۆیی', en: 'video camera', emoji: '📹' },
      { ku: 'سی دی', en: 'compact disc cd', emoji: '💿' },
      { ku: 'چاویلکەی ڤی ئاڕ', en: 'vr headset', emoji: '🥽' },
      { ku: 'کارت مێمۆری', en: 'memory card', emoji: '💾' },
      { ku: 'سێرڤەر', en: 'server rack', emoji: '🖥️' },
      { ku: 'بڵندگۆی زیرەک', en: 'smart speaker', emoji: '🔊' },
      { ku: 'کاتژمێری ئەلیکترۆنی', en: 'digital clock', emoji: '⏰' },
      { ku: 'تەرازووی ئەلیکترۆنی', en: 'digital scale', emoji: '⚖️' },
    ],
  },
  {
    id: 'kitchen', name: 'ئامێری چێشتخانە', icon: '🍳',
    words: [
      { ku: 'تاوە', en: 'frying pan', emoji: '🍳' },
      { ku: 'مەنجەڵ', en: 'cooking pot', emoji: '🍲' },
      { ku: 'فڕن', en: 'oven', emoji: '🔥' },
      { ku: 'مایکرۆوەیڤ', en: 'microwave oven', emoji: '📡' },
      { ku: 'ساردکەرەوە', en: 'refrigerator fridge', emoji: '🧊' },
      { ku: 'بەستەر', en: 'freezer', emoji: '❄️' },
      { ku: 'تەباخ', en: 'gas stove cooker', emoji: '🔥' },
      { ku: 'کتری', en: 'electric kettle', emoji: '🫖' },
      { ku: 'تۆستەر', en: 'toaster', emoji: '🍞' },
      { ku: 'خەڵاتەی کارەبایی', en: 'blender', emoji: '🥤' },
      { ku: 'میکسەر', en: 'food mixer', emoji: '🎂' },
      { ku: 'ئامێری قاوە', en: 'coffee machine', emoji: '☕' },
      { ku: 'مەکینەی قیمەکردن', en: 'meat grinder', emoji: '🥩' },
      { ku: 'قاپشۆر', en: 'dishwasher', emoji: '🍽️' },
      { ku: 'کەوچکی چێشت', en: 'serving ladle', emoji: '🥄' },
      { ku: 'تەختەی جنین', en: 'cutting board', emoji: '🔪' },
      { ku: 'ڕەندە', en: 'grater', emoji: '🧀' },
      { ku: 'پاڵاوتە', en: 'colander strainer', emoji: '🍝' },
      { ku: 'تەرازووی چێشتخانە', en: 'kitchen scale', emoji: '⚖️' },
      { ku: 'پەرداخی پێوانەکردن', en: 'measuring cup', emoji: '🥛' },
      { ku: 'سەبەتەی نان', en: 'bread basket', emoji: '🥖' },
      { ku: 'سینی', en: 'serving tray', emoji: '🍽️' },
      { ku: 'فلاسک', en: 'tea flask', emoji: '🍵' },
      { ku: 'شەکردان', en: 'sugar jar', emoji: '🍬' },
      { ku: 'پەرداخی چا', en: 'tea cup', emoji: '🍵' },
      { ku: 'فنجان', en: 'coffee mug', emoji: '☕' },
      { ku: 'سینیی هێلکە', en: 'egg tray', emoji: '🥚' },
      { ku: 'دەستکێشی فڕن', en: 'oven mitt', emoji: '🧤' },
      { ku: 'پێشبەند', en: 'apron', emoji: '🧑‍🍳' },
      { ku: 'خوێدان', en: 'salt shaker', emoji: '🧂' },
      { ku: 'هێلکەشێل', en: 'whisk', emoji: '🥚' },
      { ku: 'قەپاغی مەنجەڵ', en: 'pot lid', emoji: '🍲' },
      { ku: 'تیرۆک', en: 'rolling pin', emoji: '🥟' },
      { ku: 'سینی فڕن', en: 'baking tray', emoji: '🍪' },
      { ku: 'قاڵبی کێک', en: 'cake mold pan', emoji: '🎂' },
    ],
  },
  {
    id: 'home', name: 'ناوماڵ و کەلوپەل', icon: '🛋️',
    words: [
      { ku: 'کورسی', en: 'chair', emoji: '🪑' },
      { ku: 'مێز', en: 'table', emoji: '🪑' },
      { ku: 'قەنەفە', en: 'sofa couch', emoji: '🛋️' },
      { ku: 'تەختەخەو', en: 'bed', emoji: '🛏️' },
      { ku: 'کەنتۆر', en: 'wardrobe closet', emoji: '🚪' },
      { ku: 'ڕەفە', en: 'shelf', emoji: '📚' },
      { ku: 'ڕەفەی کتێب', en: 'bookcase', emoji: '📚' },
      { ku: 'سەرین', en: 'pillow', emoji: '🛌' },
      { ku: 'لێفە', en: 'blanket quilt', emoji: '🛏️' },
      { ku: 'دۆشەک', en: 'mattress', emoji: '🛏️' },
      { ku: 'پەردە', en: 'curtains', emoji: '🪟' },
      { ku: 'فەرش', en: 'carpet', emoji: '🟫' },
      { ku: 'گوڵدان', en: 'flower vase', emoji: '🏺' },
      { ku: 'تابلۆ', en: 'wall painting frame', emoji: '🖼️' },
      { ku: 'لۆستەر', en: 'ceiling lamp chandelier', emoji: '💡' },
      { ku: 'چرای مێز', en: 'desk lamp', emoji: '💡' },
      { ku: 'سۆپا', en: 'heater radiator', emoji: '🔥' },
      { ku: 'سپلیت', en: 'air conditioner', emoji: '❄️' },
      { ku: 'پەنکە', en: 'electric fan', emoji: '🌀' },
      { ku: 'ئاوێنەی دیوار', en: 'wall mirror', emoji: '🪞' },
      { ku: 'جلشۆر', en: 'washing machine', emoji: '🧺' },
      { ku: 'وشککەرەوە', en: 'clothes dryer', emoji: '🌬️' },
      { ku: 'قاپشۆر', en: 'dishwasher', emoji: '🍽️' },
      { ku: 'گسکەبرقی', en: 'vacuum cleaner', emoji: '🧹' },
      { ku: 'تەلەفزیۆن', en: 'living room tv', emoji: '📺' },
      { ku: 'مێزی تەلەفزیۆن', en: 'tv stand', emoji: '📺' },
      { ku: 'مێزی نووسین', en: 'desk', emoji: '🖊️' },
      { ku: 'ساردکەرەوە', en: 'fridge', emoji: '🧊' },
      { ku: 'دەستشۆر', en: 'sink basin', emoji: '🚰' },
      { ku: 'حەمام', en: 'bathtub', emoji: '🛁' },
      { ku: 'دووش', en: 'shower', emoji: '🚿' },
      { ku: 'ئاودەست', en: 'toilet', emoji: '🚽' },
      { ku: 'سەتڵی خۆڵ', en: 'trash can bin', emoji: '🗑️' },
      { ku: 'پەیژە', en: 'staircase', emoji: '🪜' },
      { ku: 'سوویچی کارەبا', en: 'light switch', emoji: '💡' },
      { ku: 'زەنگی دەرگا', en: 'doorbell', emoji: '🔔' },
      { ku: 'سندووقی پۆست', en: 'mailbox', emoji: '📬' },
      { ku: 'دەرگای شووشەیی', en: 'glass door', emoji: '🚪' },
      { ku: 'کاتژمێری دیوار', en: 'wall clock', emoji: '🕐' },
      { ku: 'قاسە', en: 'safe vault', emoji: '🔐' },
    ],
  },
  {
    id: 'school', name: 'قوتابخانە و نووسین', icon: '📚',
    words: [
      { ku: 'قەڵەمی دار', en: 'pencil', emoji: '✏️' },
      { ku: 'قەڵەمی جاف', en: 'pen', emoji: '🖊️' },
      { ku: 'کتێب', en: 'book', emoji: '📖' },
      { ku: 'دەفتەر', en: 'notebook', emoji: '📓' },
      { ku: 'لاستیک', en: 'eraser rubber', emoji: '🧽' },
      { ku: 'قەڵەمتراش', en: 'pencil sharpener', emoji: '✏️' },
      { ku: 'خەتکێش', en: 'ruler', emoji: '📏' },
      { ku: 'پەرگار', en: 'compass drawing', emoji: '🧭' },
      { ku: 'گۆشەپێو', en: 'protractor', emoji: '📐' },
      { ku: 'قەڵەمی نیشانەکردن', en: 'marker', emoji: '🖍️' },
      { ku: 'ڕەنگی مۆمی', en: 'crayons', emoji: '🖍️' },
      { ku: 'فڵچەی ڕەنگکردن', en: 'paint brush', emoji: '🖌️' },
      { ku: 'ڕەنگی ئاوی', en: 'watercolor paints', emoji: '🎨' },
      { ku: 'چەسپ', en: 'glue', emoji: '🩹' },
      { ku: 'مەقەست', en: 'scissors', emoji: '✂️' },
      { ku: 'دەرزیتەقێن', en: 'stapler', emoji: '📎' },
      { ku: 'کاغەز', en: 'paper sheet', emoji: '📄' },
      { ku: 'تەختە ڕەش', en: 'blackboard chalkboard', emoji: '🟩' },
      { ku: 'تەختە سپی', en: 'whiteboard', emoji: '⬜' },
      { ku: 'تەباشیر', en: 'chalk', emoji: '🖍️' },
      { ku: 'کۆڵەپشت', en: 'school backpack', emoji: '🎒' },
      { ku: 'قەڵەمدان', en: 'pencil case', emoji: '🖊️' },
      { ku: 'گۆی زەوی', en: 'globe map', emoji: '🌍' },
      { ku: 'نەخشە', en: 'world map', emoji: '🗺️' },
      { ku: 'حاسیبە', en: 'calculator', emoji: '🧮' },
      { ku: 'فایل', en: 'document folder', emoji: '📁' },
      { ku: 'فەرهەنگ', en: 'dictionary', emoji: '📕' },
      { ku: 'مایکرۆسکۆپ', en: 'microscope', emoji: '🔬' },
      { ku: 'تەلسکۆپ', en: 'telescope', emoji: '🔭' },
      { ku: 'کلاسەر', en: 'binder ring file', emoji: '🗂️' },
      { ku: 'دەرزیی تەختە', en: 'pushpin', emoji: '📌' },
      { ku: 'پەتەلاستیک', en: 'rubber band', emoji: '➰' },
      { ku: 'قەڵەمی فسفۆڕی', en: 'highlighter', emoji: '🖊️' },
      { ku: 'خشتەی وانەکان', en: 'class schedule', emoji: '🗓️' },
      { ku: 'بڕوانامە', en: 'school certificate', emoji: '📜' },
    ],
  },
  {
    id: 'body', name: 'لەشی مرۆڤ', icon: '🫀',
    words: [
      { ku: 'سەر', en: 'human head', emoji: '🗣️' },
      { ku: 'چاو', en: 'eye', emoji: '👁️' },
      { ku: 'گوێ', en: 'ear', emoji: '👂' },
      { ku: 'لووت', en: 'nose', emoji: '👃' },
      { ku: 'دەم', en: 'mouth', emoji: '👄' },
      { ku: 'زمان', en: 'tongue', emoji: '👅' },
      { ku: 'ددان', en: 'tooth', emoji: '🦷' },
      { ku: 'لێو', en: 'lips', emoji: '👄' },
      { ku: 'قژ', en: 'hair', emoji: '💇' },
      { ku: 'برۆ', en: 'eyebrow', emoji: '🤨' },
      { ku: 'مل', en: 'neck', emoji: '🧣' },
      { ku: 'شان', en: 'shoulder', emoji: '💪' },
      { ku: 'دەست', en: 'hand', emoji: '✋' },
      { ku: 'پەنجە', en: 'finger', emoji: '👆' },
      { ku: 'قۆڵ', en: 'arm', emoji: '💪' },
      { ku: 'ئانیشک', en: 'elbow', emoji: '💪' },
      { ku: 'سک', en: 'stomach belly', emoji: '🫃' },
      { ku: 'پشت', en: 'back body', emoji: '🔙' },
      { ku: 'قاچ', en: 'leg', emoji: '🦵' },
      { ku: 'ئەژنۆ', en: 'knee', emoji: '🦵' },
      { ku: 'پێ', en: 'foot', emoji: '🦶' },
      { ku: 'پەنجەی پێ', en: 'toe', emoji: '🦶' },
      { ku: 'دڵ', en: 'heart organ', emoji: '🫀' },
      { ku: 'سییەکان', en: 'lungs', emoji: '🫁' },
      { ku: 'مێشک', en: 'brain', emoji: '🧠' },
      { ku: 'جگەر', en: 'liver', emoji: '🫀' },
      { ku: 'گورچیلە', en: 'kidney', emoji: '🫘' },
      { ku: 'گەدە', en: 'stomach digestive', emoji: '🫃' },
      { ku: 'ئێسک', en: 'bone', emoji: '🦴' },
      { ku: 'ماسوولکە', en: 'muscle', emoji: '💪' },
      { ku: 'خوێن', en: 'blood', emoji: '🩸' },
      { ku: 'پێست', en: 'skin', emoji: '🖐️' },
      { ku: 'نەینۆک', en: 'fingernail', emoji: '💅' },
      { ku: 'ڕووخسار', en: 'face', emoji: '😊' },
      { ku: 'چەناگە', en: 'chin jaw', emoji: '🧔' },
      { ku: 'کوڵم', en: 'cheek', emoji: '😊' },
      { ku: 'نێوچەوان', en: 'forehead', emoji: '🤦' },
      { ku: 'برژانگ', en: 'eyelash', emoji: '👁️' },
      { ku: 'دەمار', en: 'nerve vein', emoji: '🧬' },
      { ku: 'بڕبڕەی پشت', en: 'spine backbone', emoji: '🦴' },
      { ku: 'مەچەک', en: 'wrist', emoji: '🤚' },
      { ku: 'پاژنەی پێ', en: 'heel', emoji: '🦶' },
      { ku: 'لەپی دەست', en: 'palm hand', emoji: '🤲' },
      { ku: 'گەروو', en: 'throat', emoji: '🗣️' },
      { ku: 'سپڵ', en: 'spleen', emoji: '🫀' },
    ],
  },
  {
    id: 'nature', name: 'سروشت', icon: '🌳',
    words: [
      { ku: 'دار', en: 'tree', emoji: '🌳' },
      { ku: 'گوڵ', en: 'flower', emoji: '🌸' },
      { ku: 'گیا', en: 'grass', emoji: '🌱' },
      { ku: 'گەڵا', en: 'leaf', emoji: '🍃' },
      { ku: 'شاخ', en: 'mountain', emoji: '⛰️' },
      { ku: 'دەریا', en: 'sea ocean', emoji: '🌊' },
      { ku: 'ڕووبار', en: 'river', emoji: '🏞️' },
      { ku: 'دەریاچە', en: 'lake', emoji: '🏞️' },
      { ku: 'تاڤگە', en: 'waterfall', emoji: '💦' },
      { ku: 'بیابان', en: 'desert sand', emoji: '🏜️' },
      { ku: 'دارستان', en: 'forest', emoji: '🌲' },
      { ku: 'دوورگە', en: 'island', emoji: '🏝️' },
      { ku: 'گرکان', en: 'volcano', emoji: '🌋' },
      { ku: 'ئەشکەوت', en: 'cave', emoji: '🕳️' },
      { ku: 'بەرد', en: 'rock stone', emoji: '🪨' },
      { ku: 'خاک', en: 'soil sand', emoji: '🏖️' },
      { ku: 'خۆر', en: 'sun', emoji: '☀️' },
      { ku: 'مانگ', en: 'moon', emoji: '🌙' },
      { ku: 'ئەستێرە', en: 'star', emoji: '⭐' },
      { ku: 'هەور', en: 'cloud', emoji: '☁️' },
      { ku: 'ئاسمان', en: 'sky', emoji: '🌌' },
      { ku: 'پەلکەزێڕینە', en: 'rainbow', emoji: '🌈' },
      { ku: 'ئاسۆ', en: 'sunrise sunset', emoji: '🌅' },
      { ku: 'دەشت', en: 'green meadow', emoji: '🌾' },
      { ku: 'گرد', en: 'hill', emoji: '🌄' },
      { ku: 'دۆڵ', en: 'valley', emoji: '🏞️' },
      { ku: 'کانی', en: 'spring water source', emoji: '⛲' },
      { ku: 'شاخە سەهۆڵین', en: 'glacier iceberg', emoji: '🧊' },
      { ku: 'باخچەی گوڵ', en: 'flower garden field', emoji: '🌷' },
      { ku: 'کێڵگەی کشتوکاڵی', en: 'crop field', emoji: '🌾' },
      { ku: 'لم', en: 'sand dune', emoji: '🏜️' },
      { ku: 'دەریای ناوەڕاست', en: 'mediterranean coast', emoji: '🏖️' },
      { ku: 'قەدی دار', en: 'tree trunk', emoji: '🪵' },
      { ku: 'ڕەگ', en: 'plant root', emoji: '🌱' },
      { ku: 'بەفر', en: 'snow', emoji: '❄️' },
      { ku: 'تەمومژ', en: 'fog mist', emoji: '🌫️' },
      { ku: 'هەسارە', en: 'planet', emoji: '🪐' },
      { ku: 'کیشوەر', en: 'continent globe', emoji: '🌍' },
      { ku: 'کەنداو', en: 'gulf bay', emoji: '🌊' },
      { ku: 'بنی دەریا', en: 'sea floor coral', emoji: '🪸' },
    ],
  },
  {
    id: 'weather', name: 'کەشوهەوا', icon: '🌦️',
    words: [
      { ku: 'باران', en: 'rain', emoji: '🌧️' },
      { ku: 'بەفر', en: 'snow', emoji: '🌨️' },
      { ku: 'با', en: 'wind', emoji: '🌬️' },
      { ku: 'هەور', en: 'cloudy sky', emoji: '☁️' },
      { ku: 'هەتاو', en: 'sunny weather', emoji: '☀️' },
      { ku: 'هەورەبرووسکە', en: 'thunderstorm lightning', emoji: '⛈️' },
      { ku: 'برووسکە', en: 'lightning bolt', emoji: '⚡' },
      { ku: 'تەم', en: 'fog mist', emoji: '🌫️' },
      { ku: 'تەرزە', en: 'hail', emoji: '🧊' },
      { ku: 'شەختە', en: 'frost', emoji: '❄️' },
      { ku: 'گەرما', en: 'hot heat wave', emoji: '🔥' },
      { ku: 'سەرما', en: 'cold freezing', emoji: '🥶' },
      { ku: 'پەلکەزێڕینە', en: 'rainbow', emoji: '🌈' },
      { ku: 'ڕەشەبا', en: 'tornado storm', emoji: '🌪️' },
      { ku: 'گەردەلوول', en: 'hurricane cyclone', emoji: '🌀' },
      { ku: 'شەپۆلی گەرما', en: 'heatwave sun', emoji: '🥵' },
      { ku: 'شێدار', en: 'humidity damp', emoji: '💧' },
      { ku: 'شەونم', en: 'morning dew', emoji: '💦' },
      { ku: 'خۆرهەڵاتن', en: 'sunrise', emoji: '🌅' },
      { ku: 'خۆرئاوابوون', en: 'sunset', emoji: '🌇' },
      { ku: 'بەهار', en: 'spring season', emoji: '🌸' },
      { ku: 'هاوین', en: 'summer season', emoji: '🌞' },
      { ku: 'پاییز', en: 'autumn fall season', emoji: '🍂' },
      { ku: 'زستان', en: 'winter season', emoji: '⛄' },
      { ku: 'تریفەی مانگ', en: 'moonlight night', emoji: '🌝' },
      { ku: 'شەپۆلی گەرم', en: 'warm breeze', emoji: '🍃' },
      { ku: 'بارانی بەخوڕ', en: 'drizzle light rain', emoji: '🌦️' },
      { ku: 'لافاو', en: 'flood', emoji: '🌊' },
      { ku: 'وشکەساڵی', en: 'drought dry land', emoji: '🏜️' },
      { ku: 'شنەبا', en: 'gentle breeze', emoji: '🌬️' },
    ],
  },
  {
    id: 'drinks', name: 'خواردنەوە و شیرینی', icon: '🍹',
    words: [
      { ku: 'ئاو', en: 'water glass', emoji: '💧' },
      { ku: 'چا', en: 'tea', emoji: '🍵' },
      { ku: 'قاوە', en: 'coffee', emoji: '☕' },
      { ku: 'شیر', en: 'milk', emoji: '🥛' },
      { ku: 'شەربەت', en: 'juice', emoji: '🧃' },
      { ku: 'شەربەتی پرتەقاڵ', en: 'orange juice', emoji: '🍊' },
      { ku: 'کۆلا', en: 'cola soda', emoji: '🥤' },
      { ku: 'لیمۆناتە', en: 'lemonade', emoji: '🍋' },
      { ku: 'سمووسی', en: 'smoothie', emoji: '🥤' },
      { ku: 'میلک شەیک', en: 'milkshake', emoji: '🥤' },
      { ku: 'دۆ', en: 'yogurt drink ayran', emoji: '🥛' },
      { ku: 'شۆکۆلاتەی گەرم', en: 'hot chocolate', emoji: '☕' },
      { ku: 'چای سەوز', en: 'green tea', emoji: '🍵' },
      { ku: 'تەمەرهیندی', en: 'tamarind drink', emoji: '🟤' },
      { ku: 'شەربەتی شووتی', en: 'watermelon juice', emoji: '🍉' },
      { ku: 'قاوەی سارد', en: 'iced coffee', emoji: '🧋' },
      { ku: 'چای بۆبا', en: 'bubble tea', emoji: '🧋' },
      { ku: 'بەستەنی', en: 'ice cream', emoji: '🍦' },
      { ku: 'جێلاتۆ', en: 'gelato', emoji: '🍨' },
      { ku: 'مۆتەی دارین', en: 'popsicle ice lolly', emoji: '🍡' },
      { ku: 'کێک', en: 'cake', emoji: '🍰' },
      { ku: 'کێکی جەژن', en: 'birthday cake', emoji: '🎂' },
      { ku: 'کلووچە', en: 'cookies', emoji: '🍪' },
      { ku: 'شۆکۆلاتە', en: 'chocolate bar', emoji: '🍫' },
      { ku: 'بەقڵاوە', en: 'baklava', emoji: '🍯' },
      { ku: 'کونافە', en: 'kunafa dessert', emoji: '🧆' },
      { ku: 'ڕەحەتلوقوم', en: 'turkish delight', emoji: '🍬' },
      { ku: 'جەلی', en: 'jelly pudding', emoji: '🍮' },
      { ku: 'کرێم کارامێل', en: 'caramel flan', emoji: '🍮' },
      { ku: 'دۆنەت', en: 'donut', emoji: '🍩' },
      { ku: 'کاپ کێک', en: 'cupcake', emoji: '🧁' },
      { ku: 'مەعمول', en: 'date filled cookie', emoji: '🍪' },
      { ku: 'حەڵوا', en: 'halva sweet', emoji: '🍯' },
      { ku: 'گەزۆ', en: 'nougat candy', emoji: '🍬' },
      { ku: 'پاستیل', en: 'gummy candy', emoji: '🍬' },
      { ku: 'مژمژە', en: 'lollipop', emoji: '🍭' },
      { ku: 'پشمەک', en: 'cotton candy', emoji: '🍭' },
      { ku: 'پای سێو', en: 'apple pie', emoji: '🥧' },
      { ku: 'پودینگ', en: 'pudding dessert', emoji: '🍮' },
      { ku: 'تیرامیسو', en: 'tiramisu', emoji: '🍰' },
    ],
  },
  {
    id: 'jobs_places', name: 'تەکنەلۆجیا و ئینتەرنێت', icon: '🌐',
    words: [
      { ku: 'ئینتەرنێت', en: 'internet globe network', emoji: '🌐' },
      { ku: 'وای فای', en: 'wifi signal', emoji: '📶' },
      { ku: 'ئیمەیڵ', en: 'email envelope', emoji: '📧' },
      { ku: 'ماڵپەڕ', en: 'website browser', emoji: '🖥️' },
      { ku: 'بەرنامە', en: 'mobile app', emoji: '📲' },
      { ku: 'هاشتاگ', en: 'hashtag', emoji: '#️⃣' },
      { ku: 'لایک', en: 'like thumbs up', emoji: '👍' },
      { ku: 'هاوبەشکردن', en: 'share button', emoji: '🔗' },
      { ku: 'شوێنکەوتووان', en: 'social media followers', emoji: '👥' },
      { ku: 'بڵاوکراوە', en: 'social media post', emoji: '📝' },
      { ku: 'وێنەی سێڵفی', en: 'selfie photo', emoji: '🤳' },
      { ku: 'ئیمۆجی', en: 'emoji face', emoji: '😀' },
      { ku: 'گیف', en: 'animated gif', emoji: '🎞️' },
      { ku: 'ڤیدیۆ', en: 'video play', emoji: '🎬' },
      { ku: 'پۆدکاست', en: 'podcast microphone', emoji: '🎙️' },
      { ku: 'پەخشی ڕاستەوخۆ', en: 'live streaming', emoji: '📡' },
      { ku: 'گەیمەر', en: 'video gamer', emoji: '🎮' },
      { ku: 'کۆد', en: 'programming code', emoji: '💻' },
      { ku: 'داتابەیس', en: 'database', emoji: '🗄️' },
      { ku: 'پاشەکەوتی هەوری', en: 'cloud storage', emoji: '☁️' },
      { ku: 'وشەی تێپەڕ', en: 'password lock', emoji: '🔐' },
      { ku: 'ڤایرۆسی کۆمپیوتەر', en: 'computer virus', emoji: '🦠' },
      { ku: 'هاکەر', en: 'hacker', emoji: '🕵️' },
      { ku: 'ڕۆبۆت', en: 'robot', emoji: '🤖' },
      { ku: 'زیرەکیی دەستکرد', en: 'artificial intelligence', emoji: '🧠' },
      { ku: 'کۆدی کیو ئاڕ', en: 'qr code', emoji: '🔲' },
      { ku: 'بارکۆد', en: 'barcode', emoji: '🏷️' },
      { ku: 'بلوتووس', en: 'bluetooth', emoji: '📲' },
      { ku: 'داگرتن', en: 'download arrow', emoji: '⬇️' },
      { ku: 'بارکردن', en: 'upload arrow', emoji: '⬆️' },
      { ku: 'وێنەی شاشە', en: 'screenshot', emoji: '📸' },
      { ku: 'تەختەکلیلی زیرەک', en: 'touch keyboard', emoji: '⌨️' },
      { ku: 'ئاگادارکردنەوە', en: 'notification bell', emoji: '🔔' },
      { ku: 'باتریی لاواز', en: 'low battery', emoji: '🪫' },
      { ku: 'کێبڵی بارگاویکردن', en: 'charging cable', emoji: '🔌' },
    ],
  },
  {
    id: 'flowers', name: 'گوڵ و ڕووەک', icon: '🌷',
    words: [
      { ku: 'گوڵی سوور', en: 'red rose', emoji: '🌹' },
      { ku: 'گوڵەبەڕۆژە', en: 'sunflower', emoji: '🌻' },
      { ku: 'لالە', en: 'tulip', emoji: '🌷' },
      { ku: 'نێرگز', en: 'daffodil', emoji: '🌼' },
      { ku: 'بەیبوون', en: 'daisy chamomile', emoji: '🌼' },
      { ku: 'زەنبەق', en: 'lily flower', emoji: '🌺' },
      { ku: 'سۆسەن', en: 'iris flower', emoji: '🌸' },
      { ku: 'یاسەمین', en: 'jasmine', emoji: '🤍' },
      { ku: 'ئۆرکید', en: 'orchid', emoji: '🌸' },
      { ku: 'گوڵی لۆتس', en: 'lotus flower', emoji: '🪷' },
      { ku: 'بنەوشە', en: 'violet flower', emoji: '🟣' },
      { ku: 'گوڵی کاکتوس', en: 'cactus flower', emoji: '🌵' },
      { ku: 'لاوەند', en: 'lavender', emoji: '💜' },
      { ku: 'سپیندار', en: 'poplar tree', emoji: '🌳' },
      { ku: 'داربەڕوو', en: 'oak tree', emoji: '🌳' },
      { ku: 'سنۆبەر', en: 'pine tree', emoji: '🌲' },
      { ku: 'دارخورما', en: 'palm tree', emoji: '🌴' },
      { ku: 'دارزەیتوون', en: 'olive tree', emoji: '🫒' },
      { ku: 'دارسێو', en: 'apple tree', emoji: '🍎' },
      { ku: 'داربی', en: 'willow tree', emoji: '🌳' },
      { ku: 'بامبۆ', en: 'bamboo', emoji: '🎋' },
      { ku: 'کاکتوس', en: 'cactus', emoji: '🌵' },
      { ku: 'دەوەن', en: 'green shrub bush', emoji: '🌿' },
      { ku: 'گەنم', en: 'wheat stalk', emoji: '🌾' },
      { ku: 'جۆ', en: 'barley', emoji: '🌾' },
      { ku: 'کێڵگەی برنج', en: 'rice paddy', emoji: '🌾' },
      { ku: 'سماق', en: 'fern leaf', emoji: '🌿' },
      { ku: 'خەزە', en: 'green moss', emoji: '🍀' },
      { ku: 'شەوەرە', en: 'four leaf clover', emoji: '🍀' },
      { ku: 'چرۆ', en: 'flowering blossom', emoji: '🌸' },
      { ku: 'دارگوێز', en: 'walnut tree', emoji: '🌰' },
      { ku: 'دارهەنار', en: 'pomegranate tree', emoji: '🌳' },
      { ku: 'دڕک', en: 'thorn bush', emoji: '🌵' },
      { ku: 'گوڵدانی ناوماڵ', en: 'potted plant', emoji: '🪴' },
      { ku: 'دارتوو', en: 'mulberry tree', emoji: '🌳' },
    ],
  },
  {
    id: 'space', name: 'گەردوون و ئاسمان', icon: '🪐',
    words: [
      { ku: 'خۆر', en: 'sun star', emoji: '☀️' },
      { ku: 'مانگ', en: 'moon', emoji: '🌙' },
      { ku: 'زەوی', en: 'planet earth', emoji: '🌍' },
      { ku: 'مەریخ', en: 'mars red planet', emoji: '🔴' },
      { ku: 'موشتەری', en: 'jupiter planet', emoji: '🪐' },
      { ku: 'کەیوان', en: 'saturn rings', emoji: '🪐' },
      { ku: 'زوهرە', en: 'venus planet', emoji: '🟡' },
      { ku: 'عوتارد', en: 'mercury planet', emoji: '⚪' },
      { ku: 'ئۆرانۆس', en: 'uranus planet', emoji: '🔵' },
      { ku: 'نێپتون', en: 'neptune planet', emoji: '🔵' },
      { ku: 'ئەستێرە', en: 'shining star', emoji: '⭐' },
      { ku: 'گەلەئەستێرە', en: 'galaxy spiral', emoji: '🌌' },
      { ku: 'ئەستێرەی کلکدار', en: 'comet', emoji: '☄️' },
      { ku: 'نەیزەک', en: 'shooting star meteor', emoji: '🌠' },
      { ku: 'کونی ڕەش', en: 'black hole', emoji: '⚫' },
      { ku: 'مووشەک', en: 'rocket', emoji: '🚀' },
      { ku: 'بۆشاییگەڕ', en: 'astronaut', emoji: '🧑‍🚀' },
      { ku: 'کئەشتیی ئاسمانی', en: 'spaceship', emoji: '🛸' },
      { ku: 'مانگی دەستکرد', en: 'satellite', emoji: '🛰️' },
      { ku: 'تەلسکۆپ', en: 'space telescope', emoji: '🔭' },
      { ku: 'وێستگەی بۆشایی ئاسمان', en: 'space station', emoji: '🛰️' },
      { ku: 'یۆفۆ', en: 'ufo flying saucer', emoji: '🛸' },
      { ku: 'گەڕۆکی بۆشایی ئاسمان', en: 'space rover', emoji: '🤖' },
      { ku: 'جلی بۆشایی ئاسمان', en: 'space suit', emoji: '👨‍🚀' },
      { ku: 'کۆمەڵەی خۆر', en: 'solar system', emoji: '☀️' },
      { ku: 'مانگی پڕ', en: 'full moon', emoji: '🌕' },
      { ku: 'مانگی یەکشەوە', en: 'crescent moon', emoji: '🌙' },
      { ku: 'خۆرگیران', en: 'solar eclipse', emoji: '🌑' },
      { ku: 'کۆمەڵە ئەستێرە', en: 'constellation stars', emoji: '✨' },
      { ku: 'ڕێگای کاکێشان', en: 'milky way', emoji: '🌌' },
    ],
  },
  {
    id: 'emotions', name: 'هەست و سۆز', icon: '😊',
    words: [
      { ku: 'دڵخۆشی', en: 'happiness joy smile', emoji: '😄' },
      { ku: 'خەم', en: 'sadness crying', emoji: '😢' },
      { ku: 'تووڕەیی', en: 'anger', emoji: '😠' },
      { ku: 'ترس', en: 'fear scared', emoji: '😱' },
      { ku: 'سەرسوڕمان', en: 'surprise shock', emoji: '😲' },
      { ku: 'پێکەنین', en: 'laughter', emoji: '😂' },
      { ku: 'خۆشەویستی', en: 'love heart', emoji: '❤️' },
      { ku: 'میهرەبانی', en: 'kindness care', emoji: '🤗' },
      { ku: 'بێزاری', en: 'boredom tired', emoji: '😑' },
      { ku: 'خەمۆکی', en: 'depression gloom', emoji: '😔' },
      { ku: 'هیوا', en: 'hope sunrise', emoji: '🌅' },
      { ku: 'بێهیوایی', en: 'despair hopeless', emoji: '😞' },
      { ku: 'دڵەڕاوکێ', en: 'anxiety worry', emoji: '😰' },
      { ku: 'هێمنی', en: 'calm peace', emoji: '😌' },
      { ku: 'شەرم', en: 'shyness embarrassed', emoji: '😳' },
      { ku: 'لەخۆباییبوون', en: 'pride confident', emoji: '😎' },
      { ku: 'ئیرەیی', en: 'jealousy envy', emoji: '😒' },
      { ku: 'پێزانین', en: 'gratitude thankful', emoji: '🙏' },
      { ku: 'پەشیمانی', en: 'regret sorry', emoji: '😟' },
      { ku: 'پەرۆشی', en: 'excitement cheer', emoji: '🤩' },
      { ku: 'نیگەرانی', en: 'concern stressed', emoji: '😨' },
      { ku: 'تامەزرۆیی', en: 'longing nostalgia', emoji: '🥺' },
      { ku: 'چاوچنۆکی', en: 'greed', emoji: '🤑' },
      { ku: 'ماندووبوون', en: 'exhaustion sleepy', emoji: '😴' },
      { ku: 'کونجکۆڵی', en: 'curiosity wondering', emoji: '🤔' },
      { ku: 'قێزکردنەوە', en: 'disgust', emoji: '🤢' },
      { ku: 'متمانە', en: 'trust confidence', emoji: '🤝' },
      { ku: 'گومان', en: 'doubt suspicion', emoji: '🤨' },
      { ku: 'دڵشکان', en: 'heartbreak', emoji: '💔' },
      { ku: 'ئامێزگرتن', en: 'comfort hug', emoji: '🫂' },
    ],
  },
  {
    id: 'abstract', name: 'بیرۆکەکان', icon: '💭',
    words: [
      { ku: 'ئازادی', en: 'freedom dove sky', emoji: '🕊️' },
      { ku: 'خەون', en: 'dream clouds', emoji: '💭' },
      { ku: 'کات', en: 'time clock', emoji: '⏰' },
      { ku: 'ڕاستی', en: 'checkmark light', emoji: '✅' },
      { ku: 'درۆ', en: 'lie mask', emoji: '🤥' },
      { ku: 'سێبەر', en: 'shadow silhouette', emoji: '👤' },
      { ku: 'بێدەنگی', en: 'silence quiet', emoji: '🤫' },
      { ku: 'ترس', en: 'fear scared', emoji: '😱' },
      { ku: 'هیوا', en: 'hope sunrise', emoji: '🌅' },
      { ku: 'یادەوەری', en: 'memory photographs', emoji: '📸' },
      { ku: 'تاریکی', en: 'darkness night', emoji: '🌑' },
      { ku: 'ڕووناکی', en: 'light bulb glow', emoji: '💡' },
      { ku: 'خۆشەویستی', en: 'love heart', emoji: '❤️' },
      { ku: 'ئاشتی', en: 'peace symbol', emoji: '☮️' },
      { ku: 'سەرکەوتن', en: 'success trophy', emoji: '🏆' },
      { ku: 'شکست', en: 'failure broken', emoji: '📉' },
      { ku: 'دادپەروەری', en: 'justice scales', emoji: '⚖️' },
      { ku: 'وزە', en: 'energy power', emoji: '⚡' },
      { ku: 'زانیاری', en: 'knowledge book', emoji: '📖' },
      { ku: 'هزر', en: 'idea thinking', emoji: '💡' },
      { ku: 'دانایی', en: 'wisdom owl', emoji: '🦉' },
      { ku: 'ئەندێشە', en: 'imagination brain', emoji: '🧠' },
      { ku: 'باوەڕ', en: 'belief faith', emoji: '🙏' },
      { ku: 'ئومێد', en: 'wish star', emoji: '🌟' },
      { ku: 'سۆز', en: 'passion fire', emoji: '🔥' },
      { ku: 'مەترسی', en: 'danger warning', emoji: '⚠️' },
      { ku: 'سەلامەتی', en: 'safety shield', emoji: '🛡️' },
      { ku: 'گەشەکردن', en: 'growth plant rising', emoji: '📈' },
      { ku: 'یەکسانی', en: 'equality balance', emoji: '⚖️' },
      { ku: 'هاوکاری', en: 'cooperation teamwork', emoji: '🤝' },
      { ku: 'چێژ', en: 'pleasure enjoyment', emoji: '😋' },
      { ku: 'ئازار', en: 'pain suffering', emoji: '😣' },
      { ku: 'سەردەم', en: 'era time period', emoji: '⌛' },
      { ku: 'چارەنووس', en: 'destiny fate', emoji: '🔮' },
      { ku: 'بەخت', en: 'luck fortune', emoji: '🍀' },
    ],
  },
  {
    id: 'jobs_tools', name: 'ئامێری ئەندازیاری و کار', icon: '🛠️',
    words: [
      { ku: 'چەکوش', en: 'hammer', emoji: '🔨' },
      { ku: 'سپانە', en: 'wrench spanner', emoji: '🔧' },
      { ku: 'دەڕنەفیس', en: 'screwdriver', emoji: '🪛' },
      { ku: 'مشار', en: 'hand saw', emoji: '🪚' },
      { ku: 'مشارەبرقی', en: 'electric chainsaw', emoji: '🪚' },
      { ku: 'درێڵ', en: 'power drill', emoji: '🛠️' },
      { ku: 'مێزی کار', en: 'workbench', emoji: '🪵' },
      { ku: 'مەتری شریتی', en: 'tape measure', emoji: '📏' },
      { ku: 'تەرازووی ئاو', en: 'spirit level', emoji: '📐' },
      { ku: 'کەلبەتین', en: 'pliers', emoji: '🗜️' },
      { ku: 'سەندان', en: 'anvil', emoji: '⚒️' },
      { ku: 'مەنگەنە', en: 'vise clamp', emoji: '🗜️' },
      { ku: 'ئامێری لێهەمکردن', en: 'welding torch', emoji: '🔥' },
      { ku: 'بزمار', en: 'nail', emoji: '📌' },
      { ku: 'بورغی', en: 'bolt screw', emoji: '🔩' },
      { ku: 'تەور', en: 'axe', emoji: '🪓' },
      { ku: 'بێڵ', en: 'shovel spade', emoji: '🪏' },
      { ku: 'شەنە', en: 'rake', emoji: '🧹' },
      { ku: 'ڕۆڵەی بۆیاخ', en: 'paint roller', emoji: '🖌️' },
      { ku: 'سەتڵی بۆیاخ', en: 'paint bucket', emoji: '🎨' },
      { ku: 'پەیژەی ئاسنین', en: 'metal ladder', emoji: '🪜' },
      { ku: 'کرێن', en: 'crane machine', emoji: '🏗️' },
      { ku: 'شۆفڵ', en: 'bulldozer', emoji: '🚜' },
      { ku: 'حەفارە', en: 'excavator digger', emoji: '🚜' },
      { ku: 'چیمەنتۆ', en: 'cement bag', emoji: '🧱' },
      { ku: 'خشت', en: 'brick', emoji: '🧱' },
      { ku: 'تەختە', en: 'wood plank', emoji: '🪵' },
      { ku: 'بۆری', en: 'metal pipe', emoji: '🔩' },
      { ku: 'کێبڵ', en: 'electric cable wire', emoji: '🔌' },
      { ku: 'کڵاوی سەلامەتی', en: 'safety helmet', emoji: '⛑️' },
      { ku: 'دەستکێشی کار', en: 'work gloves', emoji: '🧤' },
      { ku: 'ماڵە', en: 'trowel', emoji: '🧱' },
      { ku: 'پەرگاری ئاسنی', en: 'caliper compass', emoji: '📐' },
      { ku: 'سندوقی ئامێرەکان', en: 'tool box', emoji: '🧰' },
    ],
  },
  {
    id: 'shapes_colors', name: 'ڕەنگ و شێوە', icon: '🎨',
    words: [
      { ku: 'سوور', en: 'red color', emoji: '🔴' },
      { ku: 'شین', en: 'blue color', emoji: '🔵' },
      { ku: 'سەوز', en: 'green color', emoji: '🟢' },
      { ku: 'زەرد', en: 'yellow color', emoji: '🟡' },
      { ku: 'پرتەقاڵی', en: 'orange color', emoji: '🟠' },
      { ku: 'مۆر', en: 'purple color', emoji: '🟣' },
      { ku: 'قاوەیی', en: 'brown color', emoji: '🟤' },
      { ku: 'ڕەش', en: 'black color', emoji: '⚫' },
      { ku: 'سپی', en: 'white color', emoji: '⚪' },
      { ku: 'پەمەیی', en: 'pink color', emoji: '¼' },
      { ku: 'خۆڵەمێشی', en: 'gray color', emoji: '¼' },
      { ku: 'زێڕین', en: 'gold color', emoji: '🟡' },
      { ku: 'زیوین', en: 'silver color', emoji: '⚪' },
      { ku: 'تورکوازی', en: 'turquoise color', emoji: '🟦' },
      { ku: 'بازنە', en: 'circle shape', emoji: '⭕' },
      { ku: 'چوارگۆشە', en: 'square shape', emoji: '🟥' },
      { ku: 'سێگۆشە', en: 'triangle shape', emoji: '🔺' },
      { ku: 'لاکێشە', en: 'rectangle shape', emoji: '🟧' },
      { ku: 'ئەستێرە', en: 'star shape', emoji: '⭐' },
      { ku: 'دڵ', en: 'heart shape', emoji: '❤️' },
      { ku: 'هێلکەیی', en: 'oval shape', emoji: '🥚' },
      { ku: 'پێنجگۆشە', en: 'pentagon shape', emoji: '⬠' },
      { ku: 'شەشگۆشە', en: 'hexagon shape', emoji: '⬡' },
      { ku: 'مەعین', en: 'diamond rhombus shape', emoji: '🔷' },
      { ku: 'هێڵی ڕاست', en: 'straight line', emoji: '➖' },
      { ku: 'هێڵی چەماوە', en: 'curved line', emoji: '〰️' },
      { ku: 'گۆ', en: 'sphere ball', emoji: '🔵' },
      { ku: 'شەشپاڵوو', en: 'cube box shape', emoji: '🧊' },
      { ku: 'هەرەم', en: 'pyramid shape', emoji: '🔺' },
      { ku: 'لوولەک', en: 'cylinder shape', emoji: '🥫' },
    ],
  },
  {
    id: 'games_toys', name: 'یاری و کەلوپەلی منداڵان', icon: '🧸',
    words: [
      { ku: 'بووکەڵە', en: 'doll', emoji: '🪆' },
      { ku: 'ورچی فەروو', en: 'teddy bear', emoji: '🧸' },
      { ku: 'تۆپ', en: 'play ball', emoji: '⚽' },
      { ku: 'لێگۆ', en: 'lego blocks', emoji: '🧱' },
      { ku: 'پەزڵ', en: 'jigsaw puzzle', emoji: '🧩' },
      { ku: 'شەترەنج', en: 'chess game', emoji: '♟️' },
      { ku: 'داما', en: 'checkers board game', emoji: '🔴' },
      { ku: 'دۆمینۆ', en: 'dominoes', emoji: '🁢' },
      { ku: 'کارتەکانی یاری', en: 'playing cards', emoji: '🃏' },
      { ku: 'زار', en: 'dice', emoji: '🎲' },
      { ku: 'کۆلارە', en: 'kite', emoji: '🪁' },
      { ku: 'یۆیۆ', en: 'yoyo toy', emoji: '🪀' },
      { ku: 'فڕفڕە', en: 'spinning top', emoji: '🌀' },
      { ku: 'باڵۆن', en: 'balloon', emoji: '🎈' },
      { ku: 'مۆرێن', en: 'marbles', emoji: '🔵' },
      { ku: 'ئۆتۆمبێلی یاری', en: 'toy car', emoji: '🚗' },
      { ku: 'شەمەندەفەری یاری', en: 'toy train', emoji: '🚂' },
      { ku: 'ڕۆبۆتی یاری', en: 'toy robot', emoji: '🤖' },
      { ku: 'ئەسپی دارین', en: 'rocking horse', emoji: '🎠' },
      { ku: 'پەتپەتێن', en: 'jump rope', emoji: '➰' },
      { ku: 'جۆلانە', en: 'swing playground', emoji: '🛝' },
      { ku: 'خلیسکێنە', en: 'slide playground', emoji: '🛝' },
      { ku: 'دەمانچەی ئاو', en: 'water gun', emoji: '🔫' },
      { ku: 'سندوقی لم', en: 'sandbox', emoji: '🏖️' },
      { ku: 'پلەیستەیشن', en: 'game console', emoji: '🎮' },
      { ku: 'تەختەی وێنەکێشان', en: 'drawing board', emoji: '🖍️' },
      { ku: 'پەیکەری پاڵەوان', en: 'action figure', emoji: '🦸' },
      { ku: 'بەربەستەکانی یاری', en: 'building blocks', emoji: '🧱' },
      { ku: 'فیکە', en: 'toy whistle', emoji: '🎵' },
      { ku: 'سکۆتەری منداڵان', en: 'kick scooter', emoji: '🛴' },
    ],
  },
  {
    id: 'medical', name: 'پزیشکی و تەندروستی', icon: '%0',
    words: [
      { ku: 'ستێتۆسکۆپ', en: 'stethoscope', emoji: '🩺' },
      { ku: 'دەرزیی کوتان', en: 'syringe injection', emoji: '💉' },
      { ku: 'حەب', en: 'pills medicine', emoji: '💊' },
      { ku: 'تەرمۆمەتر', en: 'medical thermometer', emoji: '🌡️' },
      { ku: 'لەزگەی برین', en: 'bandage', emoji: '🩹' },
      { ku: 'جبسی ئێسک', en: 'plaster cast', emoji: '🦴' },
      { ku: 'کورسیی کەمئەندامان', en: 'wheelchair', emoji: '🦽' },
      { ku: 'دارشەق', en: 'crutches', emoji: '🩼' },
      { ku: 'ماسک', en: 'medical mask', emoji: '😷' },
      { ku: 'دەستکێشی پزیشکی', en: 'surgical gloves', emoji: '🧤' },
      { ku: 'پێوەری فشاری خوێن', en: 'blood pressure monitor', emoji: '🩺' },
      { ku: 'تیشکی ئێکس', en: 'x-ray scan', emoji: '🦴' },
      { ku: 'ئامێری هێڵکاریی دڵ', en: 'ecg heart monitor', emoji: '💓' },
      { ku: 'مایکرۆسکۆپ', en: 'lab microscope', emoji: '🔬' },
      { ku: 'بۆری تاقیکردنەوە', en: 'test tube', emoji: '🧪' },
      { ku: 'کانیۆلا', en: 'iv drip bag', emoji: '💧' },
      { ku: 'جانتای فریاکەوتن', en: 'first aid kit', emoji: '🧰' },
      { ku: 'ئامێرەکانی ددان', en: 'dental tools', emoji: '🦷' },
      { ku: 'چاوێلکەی پارێزەر', en: 'protective goggles', emoji: '🥽' },
      { ku: 'جلی نەشتەرگەری', en: 'surgical gown scrubs', emoji: '🥼' },
      { ku: 'پێوەری لێدانی دڵ', en: 'pulse oximeter', emoji: '🫀' },
      { ku: 'شیرۆپ', en: 'medicine syrup', emoji: '🧴' },
      { ku: 'جێلی پاککەرەوەی دەست', en: 'hand_sanitizer', emoji: '🧴' },
      { ku: 'لۆکەی گوێ', en: 'cotton swab', emoji: '🧼' },
      { ku: 'نەشتەری پزیشکی', en: 'scalpel surgery', emoji: '🔪' },
      { ku: 'قەرەوێڵەی نەخۆش', en: 'hospital bed', emoji: '🛏️' },
      { ku: 'ئەمبوڵانس', en: 'ambulance', emoji: '🚑' },
      { ku: 'ڤیتامین', en: 'vitamin supplement', emoji: '💊' },
      { ku: 'کیسی خوێن', en: 'blood bag donation', emoji: '🩸' },
      { ku: 'ئێم ئاڕ ئای', en: 'mri scanner', emoji: '🏥' },
      { ku: 'گوێپاککەرەوە', en: 'ear cleaning tool', emoji: '👂' },
      { ku: 'تەختەی نووسینی پزیشکی', en: 'medical chart clipboard', emoji: '📋' },
      { ku: 'کەپسول', en: 'capsule medicine', emoji: '💊' },
      { ku: 'مەرهەم', en: 'ointment cream tube', emoji: '🧴' },
      { ku: 'ڤاکسین', en: 'vaccine vial', emoji: '💉' },
    ],
  },
  {
    id: 'office', name: 'کار و ئۆفیس', icon: '🏢',
    words: [
      { ku: 'مێزی کار', en: 'office desk', emoji: '🖥️' },
      { ku: 'کورسیی ئۆفیس', en: 'office chair', emoji: '🪑' },
      { ku: 'کۆمپیوتەر', en: 'work computer', emoji: '💻' },
      { ku: 'چاپکەر', en: 'office printer', emoji: '🖨️' },
      { ku: 'تەلەفۆن', en: 'office telephone', emoji: '☎️' },
      { ku: 'فایل', en: 'document files', emoji: '📁' },
      { ku: 'کلاسەر', en: 'ring binder', emoji: '🗂️' },
      { ku: 'مۆر', en: 'rubber stamp', emoji: '📑' },
      { ku: 'دەرزیتەقێن', en: 'stapler', emoji: '📎' },
      { ku: 'گیرەکەی کاغەز', en: 'paperclips', emoji: '🖇️' },
      { ku: 'تێبینیی لکێنراو', en: 'sticky notes', emoji: '🗒️' },
      { ku: 'قەڵەمی نیشانەکردن', en: 'highlighter pens', emoji: '🖊️' },
      { ku: 'دەفتەری تێبینی', en: 'planner notebook', emoji: '📔' },
      { ku: 'حاسیبە', en: 'calculator', emoji: '🧮' },
      { ku: 'سندووقی نامەکان', en: 'inbox tray', emoji: '📥' },
      { ku: 'ئامێری وردکردنی کاغەز', en: 'paper shredder', emoji: '🗑️' },
      { ku: 'تەختەی ئاگاداری', en: 'bulletin board', emoji: '📌' },
      { ku: 'پرۆجێکتەر', en: 'meeting projector', emoji: '📽️' },
      { ku: 'تەختە سپی', en: 'whiteboard', emoji: '⬜' },
      { ku: 'فنجانی قاوە', en: 'coffee mug office', emoji: '☕' },
      { ku: 'مێزی کۆبوونەوە', en: 'conference table', emoji: '🪑' },
      { ku: 'هێڵکاریی ئاماری', en: 'business chart graph', emoji: '📊' },
      { ku: 'خشتەی کارەکان', en: 'project timeline', emoji: '📈' },
      { ku: 'کارتی کار', en: 'business card', emoji: '💳' },
      { ku: 'ناسنامەی کارمەند', en: 'employee id badge', emoji: '🪪' },
      { ku: 'گرێبەستی کار', en: 'work contract document', emoji: '📜' },
      { ku: 'لیستی ئەرکەکان', en: 'to-do checklist', emoji: '✅' },
      { ku: 'ڕۆژژمێر', en: 'desk calendar', emoji: '📅' },
      { ku: 'لاپتۆپی کار', en: 'work laptop', emoji: '💻' },
      { ku: 'فلاش مێمۆری', en: 'usb stick data', emoji: '💾' },
      { ku: 'مایکرۆفۆنی کۆنفرانس', en: 'conference microphone', emoji: '🎙️' },
      { ku: 'سکانەر', en: 'document scanner', emoji: '🖨️' },
      { ku: 'کەنتۆری فایل', en: 'filing cabinet', emoji: '🗄️' },
      { ku: 'کارتی چوونەژوورەوە', en: 'office keycard', emoji: '🔑' },
      { ku: 'قەڵەمدان', en: 'pen holder cup', emoji: '✏️' },
    ],
  },
  {
    id: 'festivals', name: 'ئاهەنگ و جەژن', icon: '🎉',
    words: [
      { ku: 'تەقێنەری کاغەز', en: 'party confetti popper', emoji: '🎉' },
      { ku: 'باڵۆن', en: 'party balloons', emoji: '🎈' },
      { ku: 'کێکی جەژن', en: 'birthday cake', emoji: '🎂' },
      { ku: 'مۆمی یادی لەدایکبوون', en: 'birthday candles', emoji: '🕯️' },
      { ku: 'دیاری', en: 'wrapped gift', emoji: '🎁' },
      { ku: 'یاریی ئاگرین', en: 'fireworks', emoji: '🎆' },
      { ku: 'ئاگری نەورۆز', en: 'newroz bonfire', emoji: '🔥' },
      { ku: 'درەختی سەری ساڵ', en: 'christmas tree', emoji: '🎄' },
      { ku: 'پاپا نوێل', en: 'santa claus', emoji: '🎅' },
      { ku: 'کڵاوی ئاهەنگ', en: 'party hat', emoji: '🎉' },
      { ku: 'فانووس', en: 'ramadan lantern', emoji: '🏮' },
      { ku: 'مانگی جەژن', en: 'eid crescent moon', emoji: '🌙' },
      { ku: 'شیرینیی جەژن', en: 'eid sweets', emoji: '🍬' },
      { ku: 'کارتی پیرۆزبایی', en: 'greeting card', emoji: '💌' },
      { ku: 'چەپکە گوڵ', en: 'flower garland', emoji: '💐' },
      { ku: 'ئاهەنگی هاوسەرگیری', en: 'wedding celebration', emoji: '💒' },
      { ku: 'ئەڵقەی هاوسەرگیری', en: 'wedding ring', emoji: '💍' },
      { ku: 'سەماکردن', en: 'dancing party', emoji: '💃' },
      { ku: 'مۆسیقای ڕاستەوخۆ', en: 'live band concert', emoji: '🎤' },
      { ku: 'فێستیڤاڵ', en: 'music festival crowd', emoji: '🎪' },
      { ku: 'ماسکی جەژن', en: 'carnival mask', emoji: '🎭' },
      { ku: 'شریتی ڕەنگین', en: 'decorative streamers', emoji: '🎊' },
      { ku: 'گڵۆپی ڕازاندنەوە', en: 'festive string lights', emoji: '💡' },
      { ku: 'تەپڵی جەژن', en: 'celebration drums', emoji: '🥁' },
      { ku: 'فیکەی ئاهەنگ', en: 'party whistle', emoji: '🎉' },
      { ku: 'بازنەی هەڵپەڕکێ', en: 'folk dance circle', emoji: '🕺' },
      { ku: 'سفرەی جەژن', en: 'feast banquet table', emoji: '🍽️' },
      { ku: 'جامی سەرکەوتن', en: 'victory trophy', emoji: '🏆' },
      { ku: 'مەدالیا', en: 'medal award', emoji: '🏅' },
      { ku: 'ئاڵای پیرۆزبایی', en: 'celebration banner', emoji: '🎌' },
    ],
  },
  {
    id: 'landmarks', name: 'شوێنە مێژووییەکان', icon: '🏛️',
    words: [
      { ku: 'تاوەری ئێفڵ', en: 'eiffel tower paris', emoji: '🗼' },
      { ku: 'ئەهرامەکانی میسر', en: 'egyptian pyramids', emoji: '🔺' },
      { ku: 'دیواری گەورەی چین', en: 'great wall of china', emoji: '🧱' },
      { ku: 'تاج مەحەل', en: 'taj mahal', emoji: '🕌' },
      { ku: 'پەیکەری ئازادی', en: 'statue of liberty', emoji: '🗽' },
      { ku: 'کۆلۆسیۆم', en: 'roman colosseum', emoji: '🏛️' },
      { ku: 'بورجی خەلیفە', en: 'burj_khalifa_dubai', emoji: '🏙️' },
      { ku: 'کاتژمێری بیگ بێن', en: 'big ben london', emoji: '🕰️' },
      { ku: 'تاوەری لاری پیزا', en: 'leaning tower of pisa', emoji: '🗼' },
      { ku: 'پەرستگای پارتینۆن', en: 'parthenon greece', emoji: '🏛️' },
      { ku: 'ماچو پیچو', en: 'machu picchu', emoji: '⛰️' },
      { ku: 'پەیکەری حەزرەتی مەسیح', en: 'christ the redeemer rio', emoji: '⛪' },
      { ku: 'ستۆنهێنج', en: 'stonehenge', emoji: '🗿' },
      { ku: 'پەیکەرەکانی دوورگەی ئیستەر', en: 'easter island statues', emoji: '🗿' },
      { ku: 'تەلاری ئۆپێرای سیدنی', en: 'sydney opera house', emoji: '🏛️' },
      { ku: 'کۆشکی کرێملین', en: 'kremlin moscow', emoji: '🏰' },
      { ku: 'مزگەوتی شێخ زاید', en: 'sheikh zayed mosque', emoji: '🕌' },
      { ku: 'کەعبە', en: 'kaaba mecca', emoji: '🕋' },
      { ku: 'قوبەی سەخرە', en: 'dome of the rock', emoji: '🕌' },
      { ku: 'شاری پێترا', en: 'petra jordan', emoji: '🏛️' },
      { ku: 'پەرستگای ئەنکۆر وات', en: 'angkor wat temple', emoji: '🛕' },
      { ku: 'پەرستگای زێڕین', en: 'golden temple', emoji: '🛕' },
      { ku: 'تاوەری تۆکیۆ', en: 'tokyo tower', emoji: '🗼' },
      { ku: 'دەروازەی براندنبۆرگ', en: 'brandenburg gate', emoji: '🏛️' },
      { ku: 'کڵێسای ساگرادا فامیلیا', en: 'sagrada familia barcelona', emoji: '⛪' },
      { ku: 'کۆشکی باکینگهام', en: 'buckingham palace', emoji: '🏰' },
      { ku: 'تاوەری شارد لە لەندەن', en: 'london shard tower', emoji: '🏙️' },
      { ku: 'قەڵای هەولێر', en: 'erbil citadel', emoji: '🏰' },
      { ku: 'شوێنەوارەکانی بابل', en: 'babylon ancient ruins', emoji: '🏛️' },
      { ku: 'منارەی حەدبا', en: 'mosul leaning minaret', emoji: '🕌' },
    ],
  },
  {
    id: 'fantasy', name: 'ئەفسانە و خەیاڵی', icon: '🐉',
    words: [
      { ku: 'ئەژدیها', en: 'dragon', emoji: '🐉' },
      { ku: 'یەکشاخ', en: 'unicorn', emoji: '🦄' },
      { ku: 'پەری', en: 'fairy', emoji: '🧚' },
      { ku: 'جادووگەر', en: 'wizard sorcerer', emoji: '🧙' },
      { ku: 'جنۆکە', en: 'genie magic lamp', emoji: '🧞' },
      { ku: 'دێو', en: 'ogre giant monster', emoji: '👹' },
      { ku: 'تارمایی', en: 'ghost', emoji: '👻' },
      { ku: 'زۆمبی', en: 'zombie', emoji: '🧟' },
      { ku: 'خوێنمژ', en: 'vampire', emoji: '🧛' },
      { ku: 'گورگ پیاو', en: 'werewolf', emoji: '🐺' },
      { ku: 'پاڵەوانی ناوازە', en: 'superhero', emoji: '🦸' },
      { ku: 'بەدکار', en: 'supervillain', emoji: '🦹' },
      { ku: 'فریشتە', en: 'angel wings', emoji: '👼' },
      { ku: 'شەیتان', en: 'devil demon', emoji: '😈' },
      { ku: 'مۆمیا', en: 'mummy', emoji: '🧟' },
      { ku: 'گسکی جادوویی', en: 'flying broomstick', emoji: '🧹' },
      { ku: 'گۆی کریستاڵی', en: 'crystal ball', emoji: '🔮' },
      { ku: 'گۆچانی جادوویی', en: 'magic wand', emoji: '🪄' },
      { ku: 'گیراوەی جادوویی', en: 'magic potion', emoji: '🧪' },
      { ku: 'کتێبی جادوو', en: 'spell book grimoire', emoji: '📖' },
      { ku: 'قەڵای ئەفسانەیی', en: 'fantasy castle', emoji: '🏰' },
      { ku: 'سندوقی گەنجینە', en: 'pirate treasure chest', emoji: '💰' },
      { ku: 'کەشتیی چەتەکانی دەریا', en: 'pirate ship', emoji: '🏴‍☠️' },
      { ku: 'چەتەی دەریا', en: 'pirate captain', emoji: '🏴‍☠️' },
      { ku: 'شازادە', en: 'fairytale princess', emoji: '👸' },
      { ku: 'پاشا', en: 'king crown', emoji: '🤴' },
      { ku: 'ماری دەریایی گەورە', en: 'sea serpent kraken', emoji: '🐙' },
      { ku: 'قاقنەس', en: 'phoenix fire bird', emoji: '🔥' },
      { ku: 'سێنتۆر', en: 'centaur', emoji: '🐎' },
      { ku: 'پەریی دەریا', en: 'mermaid', emoji: '🧜' },
      { ku: 'تڕۆڵ', en: 'troll', emoji: '🧌' },
      { ku: 'بوونەوەری شاخدار', en: 'horned beast', emoji: '🐲' },
      { ku: 'دەروازەی جادوویی', en: 'magic portal', emoji: '🌀' },
      { ku: 'ڕۆبۆتی زەبەلاح', en: 'giant robot mecha', emoji: '🤖' },
      { ku: 'بوونەوەری ئاگرین', en: 'fire breathing creature', emoji: '🔥' },
    ],
  },
  {
    id: 'symbols', name: 'نیشانە و ترافیک', icon: '🚦',
    words: [
      { ku: 'چرای هاتوچۆ', en: 'traffic light', emoji: '🚦' },
      { ku: 'هێمای وەستان', en: 'stop sign', emoji: '🛑' },
      { ku: 'پەڕینەوەی پیادە', en: 'pedestrian crossing', emoji: '🚸' },
      { ku: 'هێمای مەترسی', en: 'warning sign', emoji: '⚠️' },
      { ku: 'هێمای پارککردن', en: 'parking sign', emoji: '🅿️' },
      { ku: 'هێمای قەدەغەکراو', en: 'no entry sign', emoji: '⛔' },
      { ku: 'تیری ئاڕاستە', en: 'direction arrow sign', emoji: '➡️' },
      { ku: 'دەرچەی فریاکەوتن', en: 'emergency exit', emoji: '🚪' },
      { ku: 'هێمای تەلەفۆن', en: 'phone symbol', emoji: '📞' },
      { ku: 'هێمای وای فای', en: 'wifi symbol', emoji: '📶' },
      { ku: 'هێمای باتری', en: 'battery icon', emoji: '🔋' },
      { ku: 'هێمای دڵ', en: 'heart icon', emoji: '❤️' },
      { ku: 'هێمای ئاشتی', en: 'peace sign', emoji: '☮️' },
      { ku: 'هێمای دووبارە بەکارهێنانەوە', en: 'recycling symbol', emoji: '♻️' },
      { ku: 'هێمای ژەهراوی', en: 'biohazard symbol', emoji: '☣️' },
      { ku: 'هێمای تیشکدانەوە', en: 'radiation symbol', emoji: '☢️' },
      { ku: 'هێمای ئاگرکوژێنەرەوە', en: 'fire extinguisher sign', emoji: '🧯' },
      { ku: 'هێمای پزیشکی', en: 'medical cross sign', emoji: '⚕️' },
      { ku: 'هێمای دۆلار', en: 'dollar sign money', emoji: '💲' },
      { ku: 'هێمای یۆرۆ', en: 'euro currency sign', emoji: '💶' },
      { ku: 'هێمای بێکۆتایی', en: 'infinity symbol', emoji: '♾️' },
      { ku: 'نیشانەی پرسیار', en: 'question mark', emoji: '❓' },
      { ku: 'نیشانەی سەرسوڕمان', en: 'exclamation mark', emoji: '❗' },
      { ku: 'نیشانەی ڕاست', en: 'check mark tick', emoji: '✅' },
      { ku: 'نیشانەی هەڵە', en: 'cross mark wrong', emoji: '❌' },
      { ku: 'هێمای ئەستێرە', en: 'star symbol', emoji: '⭐' },
      { ku: 'هاشتاگ', en: 'hashtag symbol', emoji: '#️⃣' },
      { ku: 'هێمای ئەت', en: 'at sign email', emoji: '📧' },
      { ku: 'هێمای قوفڵ', en: 'lock security icon', emoji: '🔒' },
      { ku: 'قیبلەنما', en: 'compass north sign', emoji: '🧭' },
      { ku: 'هێمای مەلەکردن', en: 'swimming sign', emoji: '🏊' },
      { ku: 'هێمای تەلەفریک', en: 'cable car sign', emoji: '🚠' },
      { ku: 'هێمای فڕۆکەخانە', en: 'airport sign', emoji: '🛬' },
      { ku: 'هێمای مۆبایل قەدەغەیە', en: 'no phones sign', emoji: '📵' },
      { ku: 'هێمای جگەرەکێشان قەدەغەیە', en: 'no smoking sign', emoji: '🚭' },
    ],
  },
]

// هاوپۆلی هەڕەمەکی (بۆ هەڵبژاردن)
export const RANDOM_CATEGORY = { id: 'random', name: 'هەڕەمەکی', icon: '🎲' }

export function getCategoryById(id) {
  return CATEGORIES.find((c) => c.id === id) || CATEGORIES[0]
}

// ئەگەر 'random' بوو، هاوپۆلێکی هەڕەمەکی هەڵدەبژێرێت
export function resolveCategory(id) {
  if (id === 'random') return CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)]
  return getCategoryById(id)
}

// هەڵبژاردنی وشەیەکی هەڕەمەکی (بێ دووبارەبوونەوەی یەکسانی پێشوو)
export function pickRandomWord(category, avoidKu = null) {
  const pool = category.words.filter((w) => w.ku !== avoidKu)
  const list = pool.length ? pool : category.words
  return list[Math.floor(Math.random() * list.length)]
}

// هەڵبژاردنی وشەیەکی نزیک (هاوپۆڵ) بۆ دۆخی «متخفّی» — جیاواز لە وشە نهێنیەکە
// ساختەکار ئەم وشە نزیکە وەردەگرێت لە جیاتی وشە سەرەکییەکە، بۆیە دەتوانێت خۆی بشارێتەوە.
export function pickDecoyWord(category, secretKu) {
  const pool = category.words.filter((w) => w.ku !== secretKu)
  if (!pool.length) return null
  return pool[Math.floor(Math.random() * pool.length)]
}

// دۆزینەوەی وشە (بۆ وەرگرتنی ئیمۆجی لە ئۆنلایندا)
export function findWord(ku) {
  for (const c of CATEGORIES) {
    const w = c.words.find((x) => x.ku === ku)
    if (w) return w
  }
  return null
}