// ═══════════════════════════════════════════════════════════
//  بانکی وشەکان — ٣٠+ هاوپۆل، +١٥٠٠ وشە
//  هەر وشەیەک: ku = کوردی، en = پڕۆمپتی ئینگلیزی بۆ وێنە، emoji = ئیمۆجی
//  هەردوو شێوازی یاری (ئۆنلاین + ناوخۆیی Pass and Play) ئەم بانکە بەکاردێنن.
// ═══════════════════════════════════════════════════════════

export const CATEGORIES = [
  {
    id: 'kurdish', name: 'کوردەواری', icon: '🏔️',
    words: [
      { ku: 'جلی کوردی', en: 'kurdish traditional clothes', emoji: '👗' },
      { ku: 'جامانە', en: 'kurdish turban headscarf', emoji: '🧣' },
      { ku: 'کڵاش', en: 'handmade traditional shoe', emoji: '👞' },
      { ku: 'دەف', en: 'frame drum daf', emoji: '🥁' },
      { ku: 'تەشی', en: 'wool spindle', emoji: '🧵' },
      { ku: 'گۆزە', en: 'clay water jug', emoji: '🏺' },
      { ku: 'فەرش', en: 'handwoven carpet rug', emoji: '🟫' },
      { ku: 'تەسبیح', en: 'prayer beads', emoji: '📿' },
      { ku: 'خەنجەر', en: 'curved dagger', emoji: '🗡️' },
      { ku: 'مەشکە', en: 'leather butter churn', emoji: '🫗' },
      { ku: 'هەڵپەڕکێ', en: 'kurdish folk dance', emoji: '💃' },
      { ku: 'زڕنا', en: 'zurna wind instrument', emoji: '🎺' },
      { ku: 'نانی تەنوور', en: 'tandoor flatbread', emoji: '🫓' },
      { ku: 'قەڵا', en: 'old castle citadel', emoji: '🏰' },
      { ku: 'پشتێن', en: 'kurdish waist sash belt', emoji: '🧶' },
      { ku: 'کەوا', en: 'kurdish robe coat', emoji: '🥼' },
      { ku: 'ڕانک', en: 'kurdish baggy trousers', emoji: '👖' },
      { ku: 'سەروێن', en: 'kurdish hat headgear', emoji: '🎩' },
      { ku: 'کڵاوڕەش', en: 'black felt cap', emoji: '🧢' },
      { ku: 'پۆزەوانە', en: 'traditional ankle band', emoji: '🦵' },
      { ku: 'دەهۆڵ', en: 'large folk drum dahol', emoji: '🥁' },
      { ku: 'بلور', en: 'reed flute', emoji: '🪈' },
      { ku: 'تەمبوور', en: 'tanbur long lute', emoji: '🪕' },
      { ku: 'شمشاڵ', en: 'long shepherd flute', emoji: '🎶' },
      { ku: 'گۆرانی', en: 'kurdish folk song singing', emoji: '🎤' },
      { ku: 'لاوک', en: 'kurdish epic ballad', emoji: '🎵' },
      { ku: 'دۆڵمە', en: 'stuffed vine leaves dolma', emoji: '🍃' },
      { ku: 'کوتلک', en: 'kurdish meatball kutilk', emoji: '🍡' },
      { ku: 'ساوەر', en: 'cracked wheat bulgur', emoji: '🌾' },
      { ku: 'دۆ', en: 'yogurt drink dugh', emoji: '🥛' },
      { ku: 'گۆچان', en: 'shepherd staff stick', emoji: '🦯' },
      { ku: 'خانووی قوڕ', en: 'rural mud house', emoji: '🛖' },
      { ku: 'هەیوان', en: 'house veranda terrace', emoji: '🏡' },
      { ku: 'تەنوور', en: 'clay oven tandoor', emoji: '🔥' },
      { ku: 'دەستار', en: 'hand grinding mill stone', emoji: '⚙️' },
      { ku: 'جاجم', en: 'kurdish wool rug kilim', emoji: '🟫' },
      { ku: 'مەفرەش', en: 'storage textile bag', emoji: '👜' },
      { ku: 'گیوە', en: 'traditional cotton shoe', emoji: '🥿' },
      { ku: 'چارۆکە', en: 'woman headscarf', emoji: '🧕' },
      { ku: 'دەستبەند', en: 'embroidered wristband', emoji: '⌚' },
      { ku: 'خشڵ', en: 'gold jewelry ornaments', emoji: '💍' },
      { ku: 'شاڵ و شەپک', en: 'kurdish suit shal u shapik', emoji: '🤵' },
      { ku: 'نەورۆز', en: 'newroz spring festival fire', emoji: '🔥' },
      { ku: 'ئاگری نەورۆز', en: 'newroz bonfire celebration', emoji: '🎇' },
      { ku: 'گوڵی نەورۆز', en: 'spring red tulip flower', emoji: '🌷' },
      { ku: 'چیای بەفراوی', en: 'snowy mountain winter', emoji: '🏔️' },
      { ku: 'کانی', en: 'mountain water spring', emoji: '⛲' },
      { ku: 'دارستان', en: 'oak forest mountains', emoji: '🌲' },
      { ku: 'پاڵەوان', en: 'folk hero warrior', emoji: '⚔️' },
      { ku: 'شاعیر', en: 'kurdish poet writing', emoji: '✒️' },
      { ku: 'چەپکە گەنم', en: 'bundle of wheat harvest', emoji: '🌾' },
      { ku: 'کەنگر', en: 'mountain wild herb', emoji: '🌿' },
      { ku: 'قارچکی کێوی', en: 'mushroom morel wild', emoji: '🍄' },
      { ku: 'نانی تیری', en: 'traditional kurdish bread', emoji: '🫓' },
      { ku: 'مرەبا', en: 'fruit preserve jam', emoji: '🍯' },
      { ku: 'پەنیری کوردی', en: 'kurdish braided cheese', emoji: '🧀' },
      { ku: 'دۆشاو', en: 'grape molasses syrup', emoji: '🍯' },
      { ku: 'هەنگوین', en: 'natural mountain honey', emoji: '🍯' },
      { ku: 'گەرماوی کۆن', en: 'old public bathhouse', emoji: '🛁' },
      { ku: 'منارە', en: 'tall ancient minaret', emoji: '🕌' },
    ],
  },
  {
    id: 'places', name: 'شوێنەکان', icon: '📍',
    words: [
      { ku: 'خانوو', en: 'house home', emoji: '🏠' },
      { ku: 'قوتابخانە', en: 'school building', emoji: '🏫' },
      { ku: 'نەخۆشخانە', en: 'hospital', emoji: '🏥' },
      { ku: 'مزگەوت', en: 'mosque', emoji: '🕌' },
      { ku: 'بازاڕ', en: 'market bazaar', emoji: '🏪' },
      { ku: 'سەیرانگا', en: 'park', emoji: '🏞️' },
      { ku: 'چێشتخانە', en: 'restaurant', emoji: '🍽️' },
      { ku: 'سینەما', en: 'cinema movie theater', emoji: '🎬' },
      { ku: 'فڕۆکەخانە', en: 'airport', emoji: '✈️' },
      { ku: 'زانکۆ', en: 'university campus', emoji: '🎓' },
      { ku: 'کتێبخانە', en: 'library', emoji: '📚' },
      { ku: 'یاریگا', en: 'sports stadium', emoji: '🏟️' },
      { ku: 'باخچە', en: 'garden', emoji: '🌳' },
      { ku: 'چیا', en: 'mountain', emoji: '⛰️' },
      { ku: 'کڵێسا', en: 'church', emoji: '⛪' },
      { ku: 'مۆڵ', en: 'shopping mall', emoji: '🛍️' },
      { ku: 'بانک', en: 'bank building', emoji: '🏦' },
      { ku: 'هۆتێل', en: 'hotel', emoji: '🏨' },
      { ku: 'کافتریا', en: 'coffee shop cafe', emoji: '☕' },
      { ku: 'دەرمانخانە', en: 'pharmacy', emoji: '💊' },
      { ku: 'پۆستخانە', en: 'post office', emoji: '📮' },
      { ku: 'بنکەی پۆلیس', en: 'police station', emoji: '🚓' },
      { ku: 'بنکەی ئاگرکوژێنەوە', en: 'fire station', emoji: '🚒' },
      { ku: 'مۆزەخانە', en: 'museum', emoji: '🏛️' },
      { ku: 'باخچەی ئاژەڵان', en: 'zoo', emoji: '🦁' },
      { ku: 'شاری یاری', en: 'amusement park', emoji: '🎡' },
      { ku: 'کەناری دەریا', en: 'beach seaside', emoji: '🏖️' },
      { ku: 'دەریاچە', en: 'lake', emoji: '🏞️' },
      { ku: 'ڕووبار', en: 'river', emoji: '🏞️' },
      { ku: 'تاڤگە', en: 'waterfall', emoji: '💦' },
      { ku: 'ئەشکەوت', en: 'cave', emoji: '🕳️' },
      { ku: 'بیابان', en: 'desert', emoji: '🏜️' },
      { ku: 'دارستان', en: 'forest woods', emoji: '🌲' },
      { ku: 'دوورگە', en: 'island', emoji: '🏝️' },
      { ku: 'پردی گەورە', en: 'big bridge', emoji: '🌉' },
      { ku: 'وێستگەی شەمەندەفەر', en: 'train station', emoji: '🚉' },
      { ku: 'وێستگەی پاس', en: 'bus station', emoji: '🚌' },
      { ku: 'بەندەر', en: 'sea port harbor', emoji: '⚓' },
      { ku: 'گەراج', en: 'parking garage', emoji: '🅿️' },
      { ku: 'باڵەخانەی نووسینگەکان', en: 'office tower building', emoji: '🏢' },
      { ku: 'کارگە', en: 'factory', emoji: '🏭' },
      { ku: 'کێڵگە', en: 'farm', emoji: '🚜' },
      { ku: 'مارکێت', en: 'grocery supermarket', emoji: '🛒' },
      { ku: 'نانەواخانە', en: 'bakery', emoji: '🥖' },
      { ku: 'سەرتاشخانە', en: 'barbershop', emoji: '💈' },
      { ku: 'باخچەی ناوماڵ', en: 'backyard garden', emoji: '🌷' },
      { ku: 'مەلەوانگە', en: 'swimming pool', emoji: '🏊' },
      { ku: 'هۆڵی وەرزش', en: 'gym fitness', emoji: '🏋️' },
      { ku: 'شانۆ', en: 'theater stage', emoji: '🎭' },
      { ku: 'پێشانگای هونەری', en: 'art gallery', emoji: '🖼️' },
      { ku: 'گۆڕەپانی گشتی', en: 'public square plaza', emoji: '⛲' },
      { ku: 'گۆڕستان', en: 'cemetery graveyard', emoji: '🪦' },
      { ku: 'خانەی پلاستیکی', en: 'greenhouse plants', emoji: '🪴' },
      { ku: 'سەربازگە', en: 'military base', emoji: '🪖' },
      { ku: 'دادگا', en: 'courthouse', emoji: '⚖️' },
      { ku: 'وێستگەی سووتەمەنی', en: 'gas station', emoji: '⛽' },
      { ku: 'مۆتێل', en: 'roadside motel', emoji: '🛏️' },
      { ku: 'کلینیک', en: 'clinic', emoji: '🩺' },
      { ku: 'تاقیگە', en: 'laboratory', emoji: '🔬' },
      { ku: 'هۆڵی وەرزشیی داخراو', en: 'indoor arena', emoji: '🏟️' },
      { ku: 'باخی میوە', en: 'fruit orchard', emoji: '🍎' },
      { ku: 'دەشت', en: 'open plain field', emoji: '🌾' },
      { ku: 'سەنتەری مەساج', en: 'spa wellness center', emoji: '🛀' },
      { ku: 'لوتکەی گرد', en: 'hilltop viewpoint', emoji: '🌄' },
      { ku: 'کۆشک', en: 'palace', emoji: '🏯' },
      { ku: 'فاڕۆس', en: 'lighthouse', emoji: '🗼' },
      { ku: 'بازاڕی سەرشەقام', en: 'street market stalls', emoji: '🍉' },
      { ku: 'باخچەی ساوایان', en: 'kindergarten playground', emoji: '🛝' },
      { ku: 'هۆڵی ئاهەنگگێڕان', en: 'wedding hall', emoji: '🎉' },
    ],
  },
  {
    id: 'clothes', name: 'جلوبەرگ', icon: '👕',
    words: [
      { ku: 'کراس', en: 'shirt', emoji: '👕' },
      { ku: 'پانتۆڵ', en: 'trousers pants', emoji: '👖' },
      { ku: 'چاکەت', en: 'jacket', emoji: '🧥' },
      { ku: 'گۆرەوی', en: 'socks', emoji: '🧦' },
      { ku: 'کڵاو', en: 'cap hat', emoji: '🧢' },
      { ku: 'پێڵاو', en: 'shoes', emoji: '👟' },
      { ku: 'دەستکێش', en: 'gloves', emoji: '🧤' },
      { ku: 'ملپێچ', en: 'scarf', emoji: '🧣' },
      { ku: 'ملوانکە', en: 'necklace', emoji: '📿' },
      { ku: 'بۆینباخ', en: 'necktie', emoji: '👔' },
      { ku: 'فستانی خانمان', en: 'dress', emoji: '👗' },
      { ku: 'ئەڵقە', en: 'ring jewelry', emoji: '💍' },
      { ku: 'کەوشی ماڵەوە', en: 'sandals slippers', emoji: '🩴' },
      { ku: 'جلی مەلەکردن', en: 'swimsuit', emoji: '🩱' },
      { ku: 'پاڵتۆ', en: 'winter coat', emoji: '🧥' },
      { ku: 'تەنوورە', en: 'skirt', emoji: '👚' },
      { ku: 'بلووز', en: 'blouse', emoji: '👚' },
      { ku: 'چاکەتی خوری', en: 'wool sweater', emoji: '🧶' },
      { ku: 'هودی', en: 'hoodie', emoji: '🧥' },
      { ku: 'پانتۆڵی جینز', en: 'jeans', emoji: '👖' },
      { ku: 'شۆرت', en: 'shorts', emoji: '🩳' },
      { ku: 'تیشێرت', en: 't-shirt', emoji: '👕' },
      { ku: 'پۆتین', en: 'boots', emoji: '🥾' },
      { ku: 'پێڵاوی پاژنەبەرز', en: 'high heels', emoji: '👠' },
      { ku: 'پێڵاوی وەرزشی', en: 'sneakers', emoji: '👟' },
      { ku: 'قاییش', en: 'belt', emoji: '🪢' },
      { ku: 'کۆڵەپشت', en: 'backpack', emoji: '🎒' },
      { ku: 'جانتای دەست', en: 'handbag purse', emoji: '👜' },
      { ku: 'جزدانی پارە', en: 'wallet', emoji: '👛' },
      { ku: 'چاوێلکە', en: 'eyeglasses', emoji: '👓' },
      { ku: 'چاوێلکەی خۆر', en: 'sunglasses', emoji: '🕶️' },
      { ku: 'کاتژمێری دەستی', en: 'wristwatch', emoji: '⌚' },
      { ku: 'گوارە', en: 'earrings', emoji: '💎' },
      { ku: 'بازن', en: 'bracelet', emoji: '📿' },
      { ku: 'تاج', en: 'crown tiara', emoji: '👑' },
      { ku: 'دوگمەی قۆڵ', en: 'cufflinks', emoji: '🔗' },
      { ku: 'پیجامە', en: 'pajamas', emoji: '🛌' },
      { ku: 'کراسی خەو', en: 'nightgown', emoji: '🌙' },
      { ku: 'بۆرنووس', en: 'bathrobe', emoji: '🛁' },
      { ku: 'جلی کار', en: 'jumpsuit overall', emoji: '👷' },
      { ku: 'یونیفۆرم', en: 'uniform', emoji: '👮' },
      { ku: 'دەستار', en: 'turban', emoji: '👑' },
      { ku: 'لەچک', en: 'headscarf hijab', emoji: '🧕' },
      { ku: 'دەستکێشی زستانە', en: 'winter mittens', emoji: '🧤' },
      { ku: 'گۆرەوی درێژ', en: 'long stockings', emoji: '🧦' },
      { ku: 'باراناوی', en: 'raincoat', emoji: '🧥' },
      { ku: 'یەخە', en: 'shirt collar', emoji: '👔' },
      { ku: 'قۆپچە', en: 'button', emoji: '🔘' },
      { ku: 'زنجیر', en: 'zipper', emoji: '🤐' },
      { ku: 'فانێلەی ژێرەوە', en: 'undershirt vest', emoji: '🎽' },
    ],
  },
  {
    id: 'sports', name: 'وەرزش', icon: '⚽',
    words: [
      { ku: 'تۆپی پێ', en: 'football soccer', emoji: '⚽' },
      { ku: 'تۆپی باسکە', en: 'basketball', emoji: '🏀' },
      { ku: 'تێنس', en: 'tennis', emoji: '🎾' },
      { ku: 'مەلەکردن', en: 'swimming', emoji: '🏊' },
      { ku: 'تۆپی بالە', en: 'volleyball', emoji: '🏐' },
      { ku: 'بۆکسێن', en: 'boxing', emoji: '🥊' },
      { ku: 'پاسکیلسواری', en: 'cycling bicycle', emoji: '🚴' },
      { ku: 'زۆرانبازی', en: 'wrestling', emoji: '🤼' },
      { ku: 'گۆڵف', en: 'golf', emoji: '⛳' },
      { ku: 'تێنسی سەرمێز', en: 'table tennis', emoji: '🏓' },
      { ku: 'بەیسبۆڵ', en: 'baseball', emoji: '⚾' },
      { ku: 'هۆکی', en: 'ice hockey', emoji: '🏒' },
      { ku: 'تیرئەندازی', en: 'archery', emoji: '🏹' },
      { ku: 'ڕاکردن', en: 'running athletics', emoji: '🏃' },
      { ku: 'تۆپی دەست', en: 'handball', emoji: '🤾' },
      { ku: 'ڕاگبی', en: 'rugby', emoji: '🏉' },
      { ku: 'کریکێت', en: 'cricket', emoji: '🏏' },
      { ku: 'بادمینتۆن', en: 'badminton', emoji: '🏸' },
      { ku: 'سکی', en: 'skiing snow', emoji: '🎿' },
      { ku: 'یاریی سنۆبۆرد', en: 'snowboarding', emoji: '🏂' },
      { ku: 'تەختەی سکەیت', en: 'skateboarding', emoji: '🛹' },
      { ku: 'سکەیتی سەر چەرخ', en: 'roller skating', emoji: '🛼' },
      { ku: 'کاراتی', en: 'karate martial arts', emoji: '🥋' },
      { ku: 'جودۆ', en: 'judo', emoji: '🥋' },
      { ku: 'تایکواندۆ', en: 'taekwondo kick', emoji: '🦵' },
      { ku: 'هەڵگرتنی قورسایی', en: 'weightlifting', emoji: '🏋️' },
      { ku: 'یۆگا', en: 'yoga', emoji: '🧘' },
      { ku: 'پیلاتس', en: 'pilates exercise', emoji: '🤸' },
      { ku: 'جیمناستیک', en: 'gymnastics', emoji: '🤸' },
      { ku: 'ئەسبسواری', en: 'horse riding', emoji: '🏇' },
      { ku: 'ژێرئاوکەوتن', en: 'scuba diving', emoji: '🤿' },
      { ku: 'شەپۆلسواری', en: 'surfing waves', emoji: '🏄' },
      { ku: 'بەلەmsواری', en: 'rowing kayak', emoji: '🚣' },
      { ku: 'پاتۆناژ', en: 'figure skating ice', emoji: '⛸️' },
      { ku: 'بازدانی بەرز', en: 'high jump', emoji: '🏃' },
      { ku: 'بازدانی درێژ', en: 'long jump', emoji: '🏃' },
      { ku: 'هاویشتنی قورسایی', en: 'shot put throw', emoji: '🥌' },
      { ku: 'پێشبڕکێی ماراسۆن', en: 'marathon race', emoji: '🏃' },
      { ku: 'بلیارد', en: 'billiards pool', emoji: '🎱' },
      { ku: 'بۆڵینگ', en: 'bowling', emoji: '🎳' },
      { ku: 'دارت', en: 'darts', emoji: '🎯' },
      { ku: 'یاری شەترەنج', en: 'chess board', emoji: '♟️' },
      { ku: 'یاری پارکوور', en: 'parkour jumping', emoji: '🤸' },
      { ku: 'شاخەوانی', en: 'mountain climbing', emoji: '🧗' },
      { ku: 'چەتربازی', en: 'skydiving parachute', emoji: '🪂' },
      { ku: 'بەلەمی چارۆکەدار', en: 'sailing boat', emoji: '⛵' },
      { ku: 'جێت سکی', en: 'jet ski', emoji: '🌊' },
      { ku: 'واتەرپۆلۆ', en: 'water polo', emoji: '🤽' },
      { ku: 'سکواش', en: 'squash sport', emoji: '🎾' },
      { ku: 'شمشێربازی', en: 'fencing sword', emoji: '🤺' },
    ],
  },
  {
    id: 'food', name: 'خواردن', icon: '🍕',
    words: [
      { ku: 'پیتزا', en: 'pizza', emoji: '🍕' },
      { ku: 'دۆڵمە', en: 'stuffed vegetables dolma', emoji: '🥬' },
      { ku: 'بریانی', en: 'biryani rice', emoji: '🍚' },
      { ku: 'کەباب', en: 'kebab grilled meat', emoji: '🍢' },
      { ku: 'گەس', en: 'shawarma wrap', emoji: '🌯' },
      { ku: 'هەمبەرگر', en: 'hamburger', emoji: '🍔' },
      { ku: 'سۆشی', en: 'sushi', emoji: '🍣' },
      { ku: 'قۆزی', en: 'roasted lamb', emoji: '🍖' },
      { ku: 'یاپراخ', en: 'stuffed grape leaves', emoji: '🍃' },
      { ku: 'مریشکی برژاو', en: 'roasted chicken', emoji: '🍗' },
      { ku: 'ساندویچ', en: 'sandwich', emoji: '🥪' },
      { ku: 'ماکارۆنی', en: 'pasta spaghetti', emoji: '🍝' },
      { ku: 'زەڵاتە', en: 'salad', emoji: '🥗' },
      { ku: 'تاکۆ', en: 'taco', emoji: '🌮' },
      { ku: 'برنج', en: 'plain white rice', emoji: '🍚' },
      { ku: 'شۆربا', en: 'soup bowl', emoji: '🍲' },
      { ku: 'شۆربای نیسک', en: 'lentil soup', emoji: '🥣' },
      { ku: 'شۆربای فاسۆلیا', en: 'beans stew', emoji: '🫘' },
      { ku: 'دۆڵمەی باینجان', en: 'stuffed eggplant', emoji: '🍆' },
      { ku: 'کوبە', en: 'kibbeh bulgur', emoji: '🧆' },
      { ku: 'فەلافل', en: 'falafel', emoji: '🧆' },
      { ku: 'حوموس', en: 'hummus dip', emoji: '🥣' },
      { ku: 'مۆتەبەل', en: 'baba ganoush eggplant dip', emoji: '🍆' },
      { ku: 'تەشریب', en: 'bread soup tashreeb', emoji: '🍜' },
      { ku: 'پاچە', en: 'sheep head trotters', emoji: '🍲' },
      { ku: 'قۆرمە سەوزی', en: 'herb stew ghormeh', emoji: '🥘' },
      { ku: 'تەهچین', en: 'rice cake tahchin', emoji: '🍚' },
      { ku: 'کفتە', en: 'meatballs kofta', emoji: '🍡' },
      { ku: 'سوجوق', en: 'spicy sausage sujuk', emoji: '🌭' },
      { ku: 'نان و پەنیر', en: 'bread and cheese', emoji: '🧀' },
      { ku: 'هێلکەی سوورکراوە', en: 'fried eggs', emoji: '🍳' },
      { ku: 'ئۆملێت', en: 'omelette', emoji: '🍳' },
      { ku: 'پانکێک', en: 'pancakes', emoji: '🥞' },
      { ku: 'وافڵ', en: 'waffle', emoji: '🧇' },
      { ku: 'کرواسان', en: 'croissant', emoji: '🥐' },
      { ku: 'سەموونی فەڕەنسی', en: 'baguette bread', emoji: '🥖' },
      { ku: 'دۆنەت', en: 'donut', emoji: '🍩' },
      { ku: 'هۆت دۆگ', en: 'hot dog', emoji: '🌭' },
      { ku: 'پەتاتەی سوورکراوە', en: 'french fries', emoji: '🍟' },
      { ku: 'ناگێتس', en: 'chicken nuggets', emoji: '🍗' },
      { ku: 'لازانیا', en: 'lasagna', emoji: '🍝' },
      { ku: 'ماسیی برژاو', en: 'grilled fish', emoji: '🐟' },
      { ku: 'شەمپ', en: 'shrimp', emoji: '🦐' },
      { ku: 'نوودڵز', en: 'noodles', emoji: '🍜' },
      { ku: 'ڕامەن', en: 'ramen bowl', emoji: '🍜' },
      { ku: 'دیم سوم', en: 'dim sum dumplings', emoji: '🥟' },
      { ku: 'بۆریتۆ', en: 'burrito', emoji: '🌯' },
      { ku: 'ناچۆس', en: 'nachos', emoji: '🧀' },
      { ku: 'کاری', en: 'curry dish', emoji: '🍛' },
      { ku: 'ستەیک', en: 'beef steak', emoji: '🥩' },
      { ku: 'پڵاو', en: 'pilaf rice', emoji: '🍚' },
      { ku: 'مەقڵووبە', en: 'maqluba upside down rice', emoji: '🍚' },
      { ku: 'کشک', en: 'porridge oatmeal', emoji: '🥣' },
      { ku: 'پۆپکۆرن', en: 'popcorn', emoji: '🍿' },
      { ku: 'چپس', en: 'potato chips crisps', emoji: '🥔' },
      { ku: 'پەنیر', en: 'cheese block', emoji: '🧀' },
      { ku: 'کەرە', en: 'butter', emoji: '🧈' },
      { ku: 'مرەبا', en: 'jam marmalade', emoji: '🍓' },
      { ku: 'سۆسی تەماتە', en: 'ketchup sauce', emoji: '🍅' },
      { ku: 'مایۆنیز', en: 'mayonnaise', emoji: '🥚' },
      { ku: 'پەنیری ڤێتا', en: 'feta cheese', emoji: '🧀' },
      { ku: 'زەیتوون', en: 'olives', emoji: '🫒' },
      { ku: 'ترشیات', en: 'pickles', emoji: '🥒' },
      { ku: 'گۆشتی برژاو', en: 'roast beef', emoji: '🍖' },
      { ku: 'سۆسیج', en: 'sausage', emoji: '🌭' },
      { ku: 'بەیکن', en: 'bacon strips', emoji: '🥓' },
      { ku: 'پای', en: 'savory pie', emoji: '🥧' },
      { ku: 'کیش', en: 'quiche', emoji: '🥧' },
      { ku: 'سەمبووسە', en: 'samosa', emoji: '🥟' },
      { ku: 'بۆرەک', en: 'borek pastry', emoji: '🥐' },
      { ku: 'مەنتی', en: 'manti dumpling', emoji: '🥟' },
    ],
  },
  {
    id: 'countries', name: 'وڵاتان', icon: '🌍',
    words: [
      { ku: 'عێراق', en: 'iraq landmark', emoji: '🇮🇶' },
      { ku: 'ئەمریکا', en: 'usa statue of liberty', emoji: '🇺🇸' },
      { ku: 'فەڕەنسا', en: 'france eiffel tower', emoji: '🇫🇷' },
      { ku: 'ژاپۆن', en: 'japan mount fuji', emoji: '🇯🇵' },
      { ku: 'بەڕازیل', en: 'brazil rio', emoji: '🇧🇷' },
      { ku: 'ئیتاڵیا', en: 'italy colosseum', emoji: '🇮🇹' },
      { ku: 'ئەڵمانیا', en: 'germany brandenburg gate', emoji: '🇩🇪' },
      { ku: 'میسر', en: 'egypt pyramids', emoji: '🇪🇬' },
      { ku: 'کەنەدا', en: 'canada maple landscape', emoji: '🇨🇦' },
      { ku: 'ئیسپانیا', en: 'spain sagrada familia', emoji: '🇪🇸' },
      { ku: 'تورکیا', en: 'turkey istanbul', emoji: '🇹🇷' },
      { ku: 'ئێران', en: 'iran persepolis', emoji: '🇮🇷' },
      { ku: 'چین', en: 'china great wall', emoji: '🇨🇳' },
      { ku: 'بەریتانیا', en: 'britain big ben london', emoji: '🇬🇧' },
      { ku: 'ڕووسیا', en: 'russia red square moscow', emoji: '🇷🇺' },
      { ku: 'هیندستان', en: 'india taj mahal', emoji: '🇮🇳' },
      { ku: 'ئوسترالیا', en: 'australia opera house', emoji: '🇦🇺' },
      { ku: 'مەکسیک', en: 'mexico aztec pyramid', emoji: '🇲🇽' },
      { ku: 'یۆنان', en: 'greece parthenon', emoji: '🇬🇷' },
      { ku: 'هۆڵەندا', en: 'netherlands windmill tulips', emoji: '🇳🇱' },
      { ku: 'سوید', en: 'sweden stockholm', emoji: '🇸🇪' },
      { ku: 'نەرویج', en: 'norway fjord', emoji: '🇳🇴' },
      { ku: 'سویسرا', en: 'switzerland alps', emoji: '🇨🇭' },
      { ku: 'پۆرتوگال', en: 'portugal lisbon', emoji: '🇵🇹' },
      { ku: 'کۆریای باشوور', en: 'south korea seoul', emoji: '🇰🇷' },
      { ku: 'تایلاند', en: 'thailand temple', emoji: '🇹🇭' },
      { ku: 'ئەندەنووسیا', en: 'indonesia bali', emoji: '🇮🇩' },
      { ku: 'عەرەبستانی سعوودی', en: 'saudi arabia mecca', emoji: '🇸🇦' },
      { ku: 'ئیمارات', en: 'uae burj khalifa dubai', emoji: '🇦🇪' },
      { ku: 'سووریا', en: 'syria damascus', emoji: '🇸🇾' },
      { ku: 'لوبنان', en: 'lebanon beirut', emoji: '🇱🇧' },
      { ku: 'ئوردن', en: 'jordan petra', emoji: '🇯🇴' },
      { ku: 'فەلەستین', en: 'palestine jerusalem dome', emoji: '🇵🇸' },
      { ku: 'مەغریب', en: 'morocco marrakech', emoji: '🇲🇦' },
      { ku: 'جەزائیر', en: 'algeria', emoji: '🇩🇿' },
      { ku: 'تونس', en: 'tunisia', emoji: '🇹🇳' },
      { ku: 'لیبیا', en: 'libya desert', emoji: '🇱🇾' },
      { ku: 'سوودان', en: 'sudan nile', emoji: '🇸🇩' },
      { ku: 'ئەفریقای باشوور', en: 'south africa cape town', emoji: '🇿🇦' },
      { ku: 'نیجیریا', en: 'nigeria lagos', emoji: '🇳🇬' },
      { ku: 'کینیا', en: 'kenya safari', emoji: '🇰🇪' },
      { ku: 'ئەرژەنتین', en: 'argentina_buenos_aires', emoji: '🇦🇷' },
      { ku: 'چیلی', en: 'chile andes', emoji: '🇨🇱' },
      { ku: 'کۆڵۆمبیا', en: 'colombia', emoji: '🇨🇴' },
      { ku: 'پێرۆ', en: 'peru machu picchu', emoji: '🇵🇪' },
      { ku: 'پۆڵەندا', en: 'poland warsaw', emoji: '🇵🇱' },
      { ku: 'ئۆکرانیا', en: 'ukraine kyiv', emoji: '🇺🇦' },
      { ku: 'نەمسا', en: 'austria vienna', emoji: '🇦🇹' },
      { ku: 'بەلجیکا', en: 'belgium brussels', emoji: '🇧🇪' },
      { ku: 'دانیمارک', en: 'denmark copenhagen', emoji: '🇩🇰' },
      { ku: 'فینلاند', en: 'finland helsinki', emoji: '🇫🇮' },
      { ku: 'ئێرلەندا', en: 'ireland dublin green', emoji: '🇮🇪' },
      { ku: 'پاکستان', en: 'pakistan islamabad', emoji: '🇵🇰' },
      { ku: 'ئەفغانستان', en: 'afghanistan_kabul', emoji: '🇦🇫' },
      { ku: 'مالیزیا', en: 'malaysia kuala lumpur towers', emoji: '🇲🇾' },
      { ku: 'فیلیپین', en: 'philippines manila', emoji: '🇵🇭' },
      { ku: 'ڤێتنام', en: 'vietnam hanoi', emoji: '🇻🇳' },
      { ku: 'سینگاپوور', en: 'singapore marina bay', emoji: '🇸🇬' },
      { ku: 'نیوزیلەندا', en: 'new zealand landscape', emoji: '🇳🇿' },
      { ku: 'قەتەر', en: 'qatar doha', emoji: '🇶🇦' },
      { ku: 'کوەیت', en: 'kuwait towers', emoji: '🇰𝑤' },
      { ku: 'عومان', en: 'oman muscat', emoji: '🇴🇲' },
      { ku: 'بەحرەین', en: 'bahrain manama', emoji: '🇧🇭' },
      { ku: 'یەمەن', en: 'yemen old city', emoji: '🇾🇪' },
    ],
  },
  {
    id: 'animals', name: 'ئاژەڵان', icon: '🦁',
    words: [
      { ku: 'شێر', en: 'lion', emoji: '🦁' },
      { ku: 'پشیلە', en: 'cat', emoji: '🐱' },
      { ku: 'سەگ', en: 'dog', emoji: '🐶' },
      { ku: 'فیل', en: 'elephant', emoji: '🐘' },
      { ku: 'هەڵۆ', en: 'eagle', emoji: '🦅' },
      { ku: 'ئەسپ', en: 'horse', emoji: '🐴' },
      { ku: 'نەهەنگ', en: 'whale', emoji: '🐳' },
      { ku: 'مەیموون', en: 'monkey', emoji: '🐵' },
      { ku: 'پڵنگ', en: 'leopard', emoji: '🐆' },
      { ku: 'ورچ', en: 'bear', emoji: '🐻' },
      { ku: 'مار', en: 'snake', emoji: '🐍' },
      { ku: 'کەروێشک', en: 'rabbit', emoji: '🐰' },
      { ku: 'ڕێوی', en: 'fox', emoji: '🦊' },
      { ku: 'گورگ', en: 'wolf', emoji: '🐺' },
      { ku: 'بەبر', en: 'tiger', emoji: '🐯' },
      { ku: 'زەرافە', en: 'giraffe', emoji: '🦒' },
      { ku: 'کەرگەدەن', en: 'rhinoceros', emoji: '🦏' },
      { ku: 'ئەسپی ئاوی', en: 'hippopotamus', emoji: '🦛' },
      { ku: 'زیبرا', en: 'zebra', emoji: '🦓' },
      { ku: 'گۆریلا', en: 'gorilla', emoji: '🦍' },
      { ku: 'وەشەق', en: 'lynx wildcat', emoji: '🐈' },
      { ku: 'یوزپڵنگ', en: 'cheetah', emoji: '🐆' },
      { ku: 'مانگا', en: 'cow', emoji: '🐮' },
      { ku: 'مەڕ', en: 'sheep', emoji: '🐑' },
      { ku: 'بزن', en: 'goat', emoji: '🐐' },
      { ku: 'بەراز', en: 'pig', emoji: '🐷' },
      { ku: 'وشتر', en: 'camel', emoji: '🐫' },
      { ku: 'کەر', en: 'donkey', emoji: '🫏' },
      { ku: 'هێستر', en: 'mule', emoji: '🐴' },
      { ku: 'مشک', en: 'mouse', emoji: '🐭' },
      { ku: 'جرج', en: 'rat', emoji: '🐀' },
      { ku: 'سمۆرە', en: 'squirrel', emoji: '🐿️' },
      { ku: 'ژوژک', en: 'hedgehog', emoji: '🦔' },
      { ku: 'شەمشەمەکوێرە', en: 'bat', emoji: '🦇' },
      { ku: 'کەنگەرۆ', en: 'kangaroo', emoji: '🦘' },
      { ku: 'کۆالا', en: 'koala', emoji: '🐨' },
      { ku: 'پاندا', en: 'panda', emoji: '🐼' },
      { ku: 'تەمبەڵەکی دارستان', en: 'sloth', emoji: '🦥' },
      { ku: 'تەمساح', en: 'crocodile', emoji: '🐊' },
      { ku: 'کێسەڵ', en: 'turtle', emoji: '🐢' },
      { ku: 'مارمێلکەی ڕەنگگۆڕ', en: 'chameleon lizard', emoji: '🦎' },
      { ku: 'بۆق', en: 'frog', emoji: '🐸' },
      { ku: 'دووپشک', en: 'scorpion', emoji: '🦂' },
      { ku: 'جووچکە', en: 'chick baby chicken', emoji: '🐤' },
      { ku: 'مریشک', en: 'hen chicken', emoji: '🐔' },
      { ku: 'کەڵەشێر', en: 'rooster', emoji: '🐓' },
      { ku: 'مراوی', en: 'duck', emoji: '🦆' },
      { ku: 'قاز', en: 'goose', emoji: '🪿' },
      { ku: 'کۆتر', en: 'pigeon dove', emoji: '🕊️' },
      { ku: 'کوندەپەپوو', en: 'owl', emoji: '🦉' },
      { ku: 'تاوس', en: 'peacock', emoji: '🦚' },
      { ku: 'پەنگوین', en: 'penguin', emoji: '🐧' },
      { ku: 'فلامینگۆ', en: 'flamingo', emoji: '🦩' },
      { ku: 'تووتی', en: 'parrot', emoji: '🦜' },
      { ku: 'قرش', en: 'shark', emoji: '🦈' },
      { ku: 'دۆلفین', en: 'dolphin', emoji: '🐬' },
      { ku: 'ماسی', en: 'fish', emoji: '🐟' },
      { ku: 'ئەختەپۆت', en: 'octopus', emoji: '🐙' },
      { ku: 'قرژاڵ', en: 'crab', emoji: '🦀' },
      { ku: 'لۆبستەر', en: 'lobster', emoji: '🦞' },
      { ku: 'شەمپ', en: 'shrimp', emoji: '🦐' },
      { ku: 'بووکی دەریا', en: 'jellyfish', emoji: '🪼' },
      { ku: 'سەگی ئاوی', en: 'seal', emoji: '🦭' },
      { ku: 'هەنگ', en: 'bee', emoji: '🐝' },
      { ku: 'پەپوولە', en: 'butterfly', emoji: '🦋' },
      { ku: 'مێروولە', en: 'ant', emoji: '🐜' },
      { ku: 'جاڵجاڵۆکە', en: 'spider', emoji: '🕷️' },
      { ku: 'مێش', en: 'fly', emoji: '🪰' },
      { ku: 'مێشوولە', en: 'mosquito', emoji: '🦟' },
      { ku: 'کرم', en: 'worm', emoji: '🪱' },
      { ku: 'سیسرک', en: 'cricket grasshopper', emoji: '🦗' },
      { ku: 'خاڵخاڵۆکە', en: 'ladybug', emoji: '🐞' },
      { ku: 'شەیتانۆکە', en: 'snail', emoji: '🐌' },
      { ku: 'دایناسۆر', en: 'dinosaur', emoji: '🦖' },
    ],
  },
  {
    id: 'professions', name: 'پیشەکان', icon: '👨‍⚕️',
    words: [
      { ku: 'پزیشک', en: 'doctor', emoji: '👨‍⚕️' },
      { ku: 'مامۆستا', en: 'teacher', emoji: '👩‍🏫' },
      { ku: 'ئەندازیار', en: 'engineer', emoji: '👷' },
      { ku: 'پۆلیس', en: 'police officer', emoji: '👮' },
      { ku: 'پارێزەر', en: 'lawyer_justice', emoji: '⚖️' },
      { ku: 'شۆفێر', en: 'driver', emoji: '🚗' },
      { ku: 'وێنەگر', en: 'photographer', emoji: '📷' },
      { ku: 'وەرزشوان', en: 'athlete', emoji: '🏅' },
      { ku: 'سەرتاش', en: 'barber', emoji: '💈' },
      { ku: 'فڕۆکەوان', en: 'pilot', emoji: '🧑‍✈️' },
      { ku: 'چێشتلێنەر', en: 'chef cook', emoji: '👨‍🍳' },
      { ku: 'جووتیار', en: 'farmer', emoji: '🌾' },
      { ku: 'ئاگرکوژێنەر', en: 'firefighter', emoji: '🧑‍🚒' },
      { ku: 'نووسەر', en: 'writer_author', emoji: '✍️' },
      { ku: 'پەرستار', en: 'nurse', emoji: '👩‍⚕️' },
      { ku: 'دەرمانساز', en: 'pharmacist', emoji: '💊' },
      { ku: 'پزیشکی ددان', en: 'dentist', emoji: '🦷' },
      { ku: 'پزیشکی ئاژەڵان', en: 'veterinarian', emoji: '🐾' },
      { ku: 'زانا', en: 'scientist', emoji: '🔬' },
      { ku: 'بیرکاریزان', en: 'mathematician', emoji: '🧮' },
      { ku: 'پرۆگرامساز', en: 'programmer coder', emoji: '💻' },
      { ku: 'کارەباچی', en: 'electrician', emoji: '🔌' },
      { ku: 'وەستای بیناسازی', en: 'construction builder', emoji: '🧱' },
      { ku: 'دارتاش', en: 'carpenter', emoji: '🪚' },
      { ku: 'لوولەکێش', en: 'plumber', emoji: '🔧' },
      { ku: 'بۆیاخچی', en: 'painter_house', emoji: '🎨' },
      { ku: 'وێنەکێش', en: 'artist painter', emoji: '🖌️' },
      { ku: 'مۆسیقاژەن', en: 'musician', emoji: '🎸' },
      { ku: 'گۆرانیبێژ', en: 'singer', emoji: '🎤' },
      { ku: 'سەماکار', en: 'dancer', emoji: '💃' },
      { ku: 'ئەکتەر', en: 'actor', emoji: '🎭' },
      { ku: 'دەرهێنەر', en: 'film director', emoji: '🎬' },
      { ku: 'ڕۆژنامەنووس', en: 'journalist reporter', emoji: '📰' },
      { ku: 'پێشکەشکاری هەواڵ', en: 'news_anchor', emoji: '📺' },
      { ku: 'بازرگان', en: 'merchant trader', emoji: '💰' },
      { ku: 'فرۆشیار', en: 'salesperson cashier', emoji: '🛒' },
      { ku: 'بانکدار', en: 'banker', emoji: '🏦' },
      { ku: 'ژمێریار', en: 'accountant', emoji: '🧾' },
      { ku: 'نانەوا', en: 'baker', emoji: '🥖' },
      { ku: 'قەسساب', en: 'butcher', emoji: '🔪' },
      { ku: 'گارسۆن', en: 'waiter', emoji: '🍽️' },
      { ku: 'باخەوان', en: 'gardener', emoji: '🌱' },
      { ku: 'ماسیگر', en: 'fisherman', emoji: '🎣' },
      { ku: 'شوان', en: 'shepherd', emoji: '🐑' },
      { ku: 'سەرباز', en: 'soldier', emoji: '🪖' },
      { ku: 'دەریاوان', en: 'sailor', emoji: '⚓' },
      { ku: 'بۆشاییگەڕ', en: 'astronaut', emoji: '🧑‍🚀' },
      { ku: 'لێکۆڵەر', en: 'detective investigator', emoji: '🕵️' },
      { ku: 'پاسەوان', en: 'security guard', emoji: '💂' },
      { ku: 'پۆستەچی', en: 'mail carrier postman', emoji: '📮' },
      { ku: 'مۆدێل', en: 'fashion model', emoji: '💁' },
      { ku: 'دیزاینەر', en: 'fashion designer', emoji: '✂️' },
      { ku: 'تەلارساز', en: 'architect', emoji: '📐' },
      { ku: 'ڕاهێنەری وەرزشی', en: 'sports coach', emoji: '📣' },
      { ku: 'وەرگێڕ', en: 'translator', emoji: '🗣️' },
      { ku: 'کتێبخانەوان', en: 'librarian', emoji: '📚' },
      { ku: 'ڕابەری ئۆرکێسترا', en: 'orchestra conductor', emoji: '🎻' },
      { ku: 'جادووگەر', en: 'magician', emoji: '🎩' },
      { ku: 'کڵۆن', en: 'clown', emoji: '🤡' },
    ],
  },
  {
    id: 'fruits', name: 'میوەکان', icon: '🍎',
    words: [
      { ku: 'سێو', en: 'apple', emoji: '🍎' },
      { ku: 'مۆز', en: 'banana', emoji: '🍌' },
      { ku: 'پرتەقاڵ', en: 'orange_fruit', emoji: '🍊' },
      { ku: 'ترێ', en: 'grapes', emoji: '🍇' },
      { ku: 'شووتی', en: 'watermelon', emoji: '🍉' },
      { ku: 'هەنار', en: 'pomegranate', emoji: '🔴' },
      { ku: 'شلیک', en: 'strawberry', emoji: '🍓' },
      { ku: 'قۆخ', en: 'peach', emoji: '🍑' },
      { ku: 'هەنجیر', en: 'fig_fruit', emoji: '🟣' },
      { ku: 'قەیسی', en: 'apricot', emoji: '🟠' },
      { ku: 'گێلاس', en: 'cherry', emoji: '🍒' },
      { ku: 'ئەناناس', en: 'pineapple', emoji: '🍍' },
      { ku: 'لیمۆ', en: 'lemon', emoji: '🍋' },
      { ku: 'مانگۆ', en: 'mango', emoji: '🥭' },
      { ku: 'هەرمێ', en: 'pear', emoji: '🍐' },
      { ku: 'کیوی', en: 'kiwi_fruit', emoji: '🥝' },
      { ku: 'کاڵەک', en: 'melon_cantaloupe', emoji: '🍈' },
      { ku: 'توو', en: 'mulberry_blackberry', emoji: '🫐' },
      { ku: 'بلوبێری', en: 'blueberry', emoji: '🫐' },
      { ku: 'بەهێ', en: 'quince', emoji: '🍐' },
      { ku: 'لالەنگی', en: 'tangerine_mandarin', emoji: '🍊' },
      { ku: 'گرەیپ فروت', en: 'grapefruit', emoji: '🍊' },
      { ku: 'خورما', en: 'dates', emoji: '🟤' },
      { ku: 'گوێزی هیندی', en: 'coconut', emoji: '🥥' },
      { ku: 'ئەڤۆکادۆ', en: 'avocado', emoji: '🥑' },
      { ku: 'پاپایا', en: 'papaya', emoji: '🟠' },
      { ku: 'پاسیفلۆرا', en: 'passion_fruit', emoji: '🟣' },
      { ku: 'دراگۆن فروت', en: 'dragon_fruit', emoji: '🐉' },
      { ku: 'لیچی', en: 'lychee', emoji: '🔴' },
      { ku: 'هەڵوژە', en: 'plum', emoji: '🟣' },
      { ku: 'ئاڵوباڵو', en: 'sour_cherry', emoji: '🍒' },
      { ku: 'تووتڕەقە', en: 'raspberry', emoji: '🔴' },
      { ku: 'کرانبێری', en: 'cranberry', emoji: '🔴' },
      { ku: 'بادەم', en: 'almond', emoji: '🌰' },
      { ku: 'گوێز', en: 'walnut', emoji: '🌰' },
      { ku: 'فستق', en: 'pistachio', emoji: '🥜' },
      { ku: 'فندق', en: 'hazelnut', emoji: '🌰' },
      { ku: 'فستقی زەمینی', en: 'peanut', emoji: '🥜' },
      { ku: 'زەیتوون', en: 'olive', emoji: '🫒' },
      { ku: 'تووی ڕەش', en: 'blackberry', emoji: '🫐' },
    ],
  },
  {
    id: 'vegetables', name: 'سەوزە', icon: '🥕',
    words: [
      { ku: 'تەماتە', en: 'tomato', emoji: '🍅' },
      { ku: 'خەیار', en: 'cucumber', emoji: '🥒' },
      { ku: 'پەتاتە', en: 'potato', emoji: '🥔' },
      { ku: 'پیاز', en: 'onion', emoji: '🧅' },
      { ku: 'سیر', en: 'garlic', emoji: '🧄' },
      { ku: 'گێزەر', en: 'carrot', emoji: '🥕' },
      { ku: 'باینجان', en: 'eggplant', emoji: '🍆' },
      { ku: 'بیبەری سەوز', en: 'green_bell_pepper', emoji: '🫑' },
      { ku: 'بیبەری تیژ', en: 'hot_chili_pepper', emoji: '🌶️' },
      { ku: 'کەلەرم', en: 'cabbage', emoji: '🥬' },
      { ku: 'قەڕنابیت', en: 'cauliflower', emoji: '🥦' },
      { ku: 'برۆکۆلی', en: 'broccoli', emoji: '🥦' },
      { ku: 'کاهوو', en: 'lettuce', emoji: '🥬' },
      { ku: 'سپێناخ', en: 'spinach', emoji: '🥬' },
      { ku: 'گەنمەشامی', en: 'corn_maize', emoji: '🌽' },
      { ku: 'قارچک', en: 'mushroom', emoji: '🍄' },
      { ku: 'فاسۆلیای سەوز', en: 'green_beans', emoji: '🫛' },
      { ku: 'نۆک', en: 'chickpeas', emoji: '🟤' },
      { ku: 'نیسک', en: 'lentils', emoji: '🟠' },
      { ku: 'باقلە', en: 'fava_beans', emoji: '🫘' },
      { ku: 'پۆلکە', en: 'green_peas', emoji: '🫛' },
      { ku: 'شێلم', en: 'turnip', emoji: '🥬' },
      { ku: 'چەوەندەر', en: 'beetroot', emoji: '🟣' },
      { ku: 'تور', en: 'radish', emoji: '🔴' },
      { ku: 'کولەکە', en: 'zucchini_squash', emoji: '🥒' },
      { ku: 'کولەکەی شیرین', en: 'pumpkin', emoji: '🎃' },
      { ku: 'بامیە', en: 'okra', emoji: '🟢' },
      { ku: 'کەرەوز', en: 'celery', emoji: '🥬' },
      { ku: 'مەعدەنووس', en: 'parsley_herb', emoji: '🌿' },
      { ku: 'کەزوەر', en: 'cilantro_coriander', emoji: '🌿' },
      { ku: 'پیازچە', en: 'green_onion_scallion', emoji: '🌱' },
      { ku: 'پونگە', en: 'mint_leaves', emoji: '🌿' },
      { ku: 'ڕێحانە', en: 'basil', emoji: '🌿' },
      { ku: 'زەنجەبیل', en: 'ginger_root', emoji: '🫚' },
      { ku: 'زەردەچەوە', en: 'turmeric', emoji: '🟡' },
      { ku: 'ئەرتیشۆک', en: 'artichoke', emoji: '🌿' },
      { ku: 'مارچۆبە', en: 'asparagus', emoji: '🥬' },
      { ku: 'پەتاتەی شیرین', en: 'sweet_potato', emoji: '🍠' },
      { ku: 'لۆبیا', en: 'kidney_beans', emoji: '🫘' },
      { ku: 'بیبەری ڕەنگاوڕەنگ', en: 'colorful_peppers', emoji: '🫑' },
    ],
  },
  {
    id: 'objects', name: 'ئامێر و شتومەک', icon: '🔧',
    words: [
      { ku: 'دەرزی', en: 'sewing_needle', emoji: '🪡' },
      { ku: 'مەقەست', en: 'scissors', emoji: '✂️' },
      { ku: 'قوفڵ', en: 'padlock', emoji: '🔒' },
      { ku: 'کلیل', en: 'key', emoji: '🔑' },
      { ku: 'پەرداخ', en: 'drinking_glass', emoji: '🥛' },
      { ku: 'قاپ', en: 'plate_dish', emoji: '🍽️' },
      { ku: 'کەوچک', en: 'spoon', emoji: '🥄' },
      { ku: 'چەقۆ', en: 'knife', emoji: '🔪' },
      { ku: 'خاولی', en: 'towel', emoji: '🧻' },
      { ku: 'پاڵاوتە', en: 'kitchen_strainer', emoji: '🧺' },
      { ku: 'چەتر', en: 'umbrella', emoji: '☂️' },
      { ku: 'مۆبایل', en: 'mobile_phone', emoji: '📱' },
      { ku: 'کاتژمێر', en: 'wristwatch', emoji: '⌚' },
      { ku: 'مۆم', en: 'candle', emoji: '🕯️' },
      { ku: 'چەتاڵ', en: 'fork', emoji: '🍴' },
      { ku: 'سپانە', en: 'wrench', emoji: '🔧' },
      { ku: 'مشار', en: 'saw_tool', emoji: '🪚' },
      { ku: 'چەکوش', en: 'hammer', emoji: '🔨' },
      { ku: 'بزمار', en: 'nail', emoji: '📌' },
      { ku: 'دەڕنەفیس', en: 'screwdriver', emoji: '🪛' },
      { ku: 'بورغی', en: 'screw_bolt', emoji: '🔩' },
      { ku: 'مەتر', en: 'tape_measure_ruler', emoji: '📏' },
      { ku: 'فڵچە', en: 'paint_brush', emoji: '🖌️' },
      { ku: 'سەتڵ', en: 'bucket', emoji: '🪣' },
      { ku: 'گسک', en: 'broom', emoji: '🧹' },
      { ku: 'ئیسفەنج', en: 'sponge', emoji: '🧽' },
      { ku: 'سابوون', en: 'soap_bar', emoji: '🧼' },
      { ku: 'فڵچەی ددان', en: 'toothbrush', emoji: '🪥' },
      { ku: 'شانە', en: 'comb', emoji: '💈' },
      { ku: 'ئاوێنە', en: 'mirror', emoji: '🪞' },
      { ku: 'چرای دەستی', en: 'flashlight', emoji: '🔦' },
      { ku: 'باتری', en: 'battery', emoji: '🔋' },
      { ku: 'گڵۆپ', en: 'light_bulb', emoji: '💡' },
      { ku: 'پلاک', en: 'electric_plug', emoji: '🔌' },
      { ku: 'نەینۆکبڕ', en: 'nail_clipper', emoji: '💅' },
      { ku: 'دەرزیتەقێن', en: 'stapler', emoji: '📎' },
      { ku: 'گیرەکەی کاغەز', en: 'paperclip', emoji: '🖇️' },
      { ku: 'پەنجەرە', en: 'window', emoji: '🪟' },
      { ku: 'دەرگا', en: 'door', emoji: '🚪' },
      { ku: 'پەیژە', en: 'ladder', emoji: '🪜' },
      { ku: 'چەمچە', en: 'ladle', emoji: '🥄' },
      { ku: 'قەفەس', en: 'cage', emoji: '🪤' },
      { ku: 'سندووق', en: 'box_crate', emoji: '📦' },
      { ku: 'چەمەدان', en: 'suitcase', emoji: '🧳' },
      { ku: 'جانتای دەستی', en: 'bag', emoji: '👜' },
      { ku: 'تەرازوو', en: 'weighing_scale', emoji: '⚖️' },
      { ku: 'دووربین', en: 'binoculars', emoji: '🔭' },
      { ku: 'زەڕەبین', en: 'magnifying_glass', emoji: '🔍' },
      { ku: 'تەرمۆمەتر', en: 'thermometer', emoji: '🌡️' },
      { ku: 'چەتری کەنار دەریا', en: 'beach_umbrella', emoji: '🏖️' },
      { ku: 'باوەشێن', en: 'hand_fan', emoji: '🪭' },
      { ku: 'سندووقی پۆست', en: 'mailbox', emoji: '📭' },
      { ku: 'زەنگ', en: 'bell', emoji: '🔔' },
      { ku: 'زنجیر', en: 'chain', emoji: '⛓️' },
      { ku: 'گرێ', en: 'rope_knot', emoji: '🪢' },
      { ku: 'تەلەفزیۆن', en: 'television', emoji: '📺' },
      { ku: 'ڕادیۆ', en: 'radio', emoji: '📻' },
      { ku: 'تەلەفۆن', en: 'landline_phone', emoji: '☎️' },
      { ku: 'کامێرا', en: 'camera', emoji: '📷' },
      { ku: 'قوتووی شووشەیی', en: 'glass_jar', emoji: '🫙' },
      { ku: 'بوتڵ', en: 'bottle', emoji: '🍾' },
      { ku: 'فلاسک', en: 'thermos_flask', emoji: '🍵' },
      { ku: 'قۆری', en: 'teapot', emoji: '🫖' },
      { ku: 'مەنقەڵ', en: 'charcoal_grill', emoji: '🔥' },
    ],
  },
  {
    id: 'sea', name: 'گیانلەبەری دەریایی', icon: '🐠',
    words: [
      { ku: 'ماسی', en: 'fish', emoji: '🐟' },
      { ku: 'ماسیی کەمەرەیی', en: 'tropical_fish', emoji: '🐠' },
      { ku: 'قرش', en: 'shark', emoji: '🦈' },
      { ku: 'نەهەنگ', en: 'whale', emoji: '🐳' },
      { ku: 'دۆلفین', en: 'dolphin', emoji: '🐬' },
      { ku: 'ئەختەپۆت', en: 'octopus', emoji: '🐙' },
      { ku: 'بووکی دەریا', en: 'jellyfish', emoji: '🪼' },
      { ku: 'کێسەڵی دەریا', en: 'sea_turtle', emoji: '🐢' },
      { ku: 'قرژاڵ', en: 'crab', emoji: '🦀' },
      { ku: 'لۆبستەر', en: 'lobster', emoji: '🦞' },
      { ku: 'شەمپ', en: 'shrimp', emoji: '🦐' },
      { ku: 'سەگی ئاوی', en: 'seal', emoji: '🦭' },
      { ku: 'ئەستێرەی دەریا', en: 'starfish', emoji: '⭐' },
      { ku: 'ئەسپی دەریا', en: 'seahorse', emoji: '🌊' },
      { ku: 'سەدەفی مرواری', en: 'pearl_oyster', emoji: '🦪' },
      { ku: 'ماری ئاوی', en: 'eel', emoji: '🐍' },
      { ku: 'ماسیی شمشێری', en: 'swordfish', emoji: '🗡️' },
      { ku: 'ماسیی تۆن', en: 'tuna_fish', emoji: '🐟' },
      { ku: 'ماسیی سەلەمۆن', en: 'salmon', emoji: '🐟' },
      { ku: 'مەرجان', en: 'coral_reef', emoji: '🪸' },
      { ku: 'حەبار', en: 'squid', emoji: '🦑' },
      { ku: 'پەنگ